import catalogImages from "./catalog-images.json";

export type Experience = "Culture" | "Nature" | "Adventure" | "Wildlife" | "Food" | "Romance" | "History" | "Beach" | "Luxury";

export interface Destination {
  name: string;
  slug: string;
  continent: string;
  tagline: string;
  description: string;
  highlights: string[];
  experiences: Experience[];
  duration: string;
  bestTime: string;
  image: string;
  heroImage: string;
  /** Catalog id from 365tours.in (e.g. "365T_00002") */
  id?: string;
  /** Real destination photos scraped from 365tours.in (local /destinations/… paths) */
  gallery?: string[];
  /** Country flag image (local path) */
  flag?: string;
  /** Regions / cities offered within this destination */
  regions?: string[];
}

type CatalogEntry = {
  id: string;
  gallery: string[];
  recipeImage: string;
  flag: string;
  regions: string[];
};

const catalog = catalogImages as Record<string, CatalogEntry>;

export const destinations: Destination[] = [
  {
    name: "Antarctica",
    slug: "antarctica",
    continent: "Antarctica",
    tagline: "The last great wilderness on Earth",
    description: "Antarctica is the ultimate frontier — a land of staggering ice formations, enormous penguin colonies, and an otherworldly silence that changes travellers forever. 365 Tours crafts exclusive expedition itineraries that take you to the edge of the world in extraordinary comfort.",
    highlights: ["Penguin colonies at close range", "Glacial zodiac cruises", "Antarctic Peninsula landscapes", "Aurora Australis viewing", "Research station visits"],
    experiences: ["Adventure", "Nature", "Luxury"],
    duration: "14–21 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1551085254-e96b210db58a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1551085254-e96b210db58a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Argentina",
    slug: "argentina",
    continent: "South America",
    tagline: "Tango, Patagonia & Gaucho culture",
    description: "Argentina is a land of sweeping contrasts — the cosmopolitan energy of Buenos Aires, the surreal ice fields of Patagonia, the Andean wine valleys of Mendoza, and the thundering Iguazu Falls. 365 Tours builds private itineraries that capture Argentina's full, dramatic range.",
    highlights: ["Iguazu Falls at sunrise", "Perito Moreno Glacier", "Buenos Aires tango culture", "Mendoza wine estates", "Patagonia trekking"],
    experiences: ["Nature", "Adventure", "Food", "Culture"],
    duration: "12–18 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Armenia",
    slug: "armenia",
    continent: "Asia",
    tagline: "Ancient monasteries & Caucasus highlands",
    description: "One of the world's oldest Christian nations, Armenia is a land of 4th-century monasteries perched on cliffsides, volcanic highland plateaus, and a capital city with extraordinary food and nightlife. An undiscovered gem on the 365 Tours circuit.",
    highlights: ["Geghard Monastery", "Lake Sevan", "Yerevan's Republic Square", "Mount Ararat views", "Noravank Canyon"],
    experiences: ["History", "Culture", "Nature"],
    duration: "8–12 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Australia",
    slug: "australia",
    continent: "Oceania",
    tagline: "Red deserts, coral reefs & iconic cities",
    description: "Australia rewards every kind of traveller — from the Great Barrier Reef and the Daintree Rainforest to the red rock of Uluru and the cosmopolitan streets of Sydney and Melbourne. 365 Tours designs private road trips and fly-drive tours across this enormous continent.",
    highlights: ["Great Barrier Reef snorkelling", "Uluru at sunrise", "Sydney Opera House", "Daintree Rainforest", "Great Ocean Road"],
    experiences: ["Nature", "Adventure", "Beach", "Culture"],
    duration: "14–21 days",
    bestTime: "September – November",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Austria",
    slug: "austria",
    continent: "Europe",
    tagline: "Mozart, Alps & Viennese grandeur",
    description: "Austria blends imperial grandeur with alpine splendour. Vienna's coffee house culture, Mozart's Salzburg, the Hallstatt lake village, and the Tyrol ski resorts make Austria a year-round destination for culture and nature lovers alike.",
    highlights: ["Vienna's Schönbrunn Palace", "Hallstatt village", "Salzburg Old Town", "Sound of Music trail", "Alpine skiing in Innsbruck"],
    experiences: ["Culture", "History", "Nature", "Luxury"],
    duration: "8–12 days",
    bestTime: "May – September & December",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Azerbaijan",
    slug: "azerbaijan",
    continent: "Asia",
    tagline: "Fire temples, mud volcanoes & the Caspian",
    description: "Where Europe meets Asia, Azerbaijan offers one of travel's most underrated experiences — ancient fire temples, surreal mud volcanoes, the futuristic Baku skyline, and carpet-weaving villages in the Caucasus Mountains. An extraordinary private tour destination.",
    highlights: ["Baku Old City (Icheri Sheher)", "Gobustan Mud Volcanoes", "Ateshgah Fire Temple", "Sheki Khan's Palace", "Caspian Sea coast"],
    experiences: ["Culture", "History", "Adventure"],
    duration: "7–10 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Belize",
    slug: "belize",
    continent: "Central America",
    tagline: "Mayan ruins, blue holes & jungle lodges",
    description: "Belize packs incredible diversity into a small country — the Great Blue Hole for divers, Mayan ruins deep in jungle, Garifuna culture along the coast, and one of the most biodiverse ecosystems in the Americas. Ideal for an intimate, off-the-beaten-path adventure.",
    highlights: ["Great Blue Hole diving", "Actun Tunichil Muknal cave", "Tikal day trip", "Caye Caulker relaxation", "Howler Monkey watching"],
    experiences: ["Adventure", "Nature", "History", "Beach"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bhutan",
    slug: "bhutan",
    continent: "Asia",
    tagline: "Gross National Happiness & Tiger's Nest",
    description: "Bhutan is the world's last Himalayan Buddhist kingdom — a land where development is measured by happiness, forests cover 70% of the country, and ancient dzongs perch above rushing rivers. 365 Tours crafts intimate, high-value Bhutan journeys with expert cultural guides.",
    highlights: ["Tiger's Nest Monastery (Paro Taktsang)", "Punakha Dzong", "Dochula Pass rhododendron forests", "Thimphu weekend market", "Black-necked crane festival"],
    experiences: ["Culture", "Nature", "History", "Adventure"],
    duration: "8–12 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1553958700-2e1e6db4114d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1553958700-2e1e6db4114d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bolivia",
    slug: "bolivia",
    continent: "South America",
    tagline: "Salt flats, altiplano & Amazon headwaters",
    description: "Bolivia is one of South America's most dramatic destinations — the mirror-like Salar de Uyuni salt flats, the highest navigable lake in the world, and the lush Amazon basin all in one country. A private Bolivia tour with 365 is a journey to the extremes.",
    highlights: ["Salar de Uyuni salt flats", "Lake Titicaca", "Death Road cycling", "La Paz witches' market", "Madidi National Park"],
    experiences: ["Adventure", "Nature", "Culture"],
    duration: "10–14 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1580492516014-4a28729eb08e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580492516014-4a28729eb08e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Botswana",
    slug: "botswana",
    continent: "Africa",
    tagline: "Okavango Delta & exclusive bush camps",
    description: "Botswana is the gold standard of African safari — exclusive, low-impact, and extraordinarily wildlife-rich. The Okavango Delta, Chobe River, and Kalahari Desert host lions, elephants, wild dogs, and hippos. 365 Tours places you in private camps for unmatched encounters.",
    highlights: ["Okavango Delta mokoro canoe", "Chobe National Park elephants", "Moremi Game Reserve", "Makgadikgadi Pans", "Wild dog sightings"],
    experiences: ["Wildlife", "Nature", "Luxury", "Adventure"],
    duration: "10–16 days",
    bestTime: "June – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Brazil",
    slug: "brazil",
    continent: "South America",
    tagline: "Amazon, Carnival & tropical coastlines",
    description: "Brazil is the world's most biodiverse country and one of its most exuberant cultures. Explore the Amazon River basin by boat, dance at Rio Carnival, walk the dunes of Lençóis Maranhenses, or relax on Florianópolis beaches. 365 Tours brings you Brazil's many faces.",
    highlights: ["Amazon River expedition", "Rio de Janeiro & Christ the Redeemer", "Iguazu Falls (Brazilian side)", "Pantanal jaguar safari", "Salvador's Afro-Brazilian culture"],
    experiences: ["Nature", "Wildlife", "Culture", "Beach", "Adventure"],
    duration: "14–21 days",
    bestTime: "April – September",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bulgaria",
    slug: "bulgaria",
    continent: "Europe",
    tagline: "Rose valleys, monasteries & Black Sea beaches",
    description: "Bulgaria is Eastern Europe's most underrated gem — ancient Thracian tombs, rose oil festivals, Orthodox monasteries in mountain gorges, and a Black Sea coast with sandy beaches and warm water. A fascinating private tour destination.",
    highlights: ["Rila Monastery", "Plovdiv Old Town", "Rose Valley festival", "Belogradchik Rocks", "Nessebar Old Town"],
    experiences: ["History", "Culture", "Nature", "Beach"],
    duration: "8–12 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1601392842425-6b8a6f7d3a2a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1601392842425-6b8a6f7d3a2a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cambodia",
    slug: "cambodia",
    continent: "Asia",
    tagline: "Angkor Wat & Mekong river life",
    description: "Cambodia's crown jewel is Angkor Wat — the world's largest religious monument — but the kingdom offers far more: floating villages on Tonle Sap Lake, the silver pagodas of Phnom Penh, and the unspoiled beaches of Koh Rong. A deeply moving destination.",
    highlights: ["Angkor Wat sunrise", "Bayon temple faces", "Tonle Sap floating village", "Royal Palace Phnom Penh", "Koh Rong beaches"],
    experiences: ["History", "Culture", "Nature", "Beach"],
    duration: "8–12 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1540428296098-3e6d5e3b3d3e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1540428296098-3e6d5e3b3d3e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Chile",
    slug: "chile",
    continent: "South America",
    tagline: "Patagonia, Atacama & Easter Island",
    description: "Chile stretches from the driest desert on Earth to the wild glaciers of Patagonia — and Easter Island sits 3,700 km out to sea. 365 Tours designs private fly-drive adventures across this extraordinary vertical country, combining multiple ecosystems in a single trip.",
    highlights: ["Torres del Paine trekking", "Atacama stargazing", "Easter Island moai", "Valle de la Luna", "Chiloé Island culture"],
    experiences: ["Adventure", "Nature", "Culture", "History"],
    duration: "14–21 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "China",
    slug: "china",
    continent: "Asia",
    tagline: "The Great Wall, silk roads & ancient dynasties",
    description: "China's sheer scale and diversity is staggering — the Great Wall, the Terracotta Army, the karst peaks of Guilin, the Tibetan plateau, and the megacities of Shanghai and Beijing. 365 Tours crafts private journeys through China's most compelling chapters.",
    highlights: ["Great Wall at Mutianyu", "Terracotta Army, Xi'an", "Li River cruise, Guilin", "Shanghai Bund", "Zhangjiajie glass bridge"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "14–21 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Colombia",
    slug: "colombia",
    continent: "South America",
    tagline: "Cartagena, coffee country & the Amazon",
    description: "Colombia has emerged as one of the world's most exciting travel destinations — the colonial grandeur of Cartagena, the coffee haciendas of Salento, the street art of Medellín, and the bird-rich Amazon. A private Colombia tour reveals a country transformed.",
    highlights: ["Cartagena's walled old city", "Salento coffee farm tour", "Medellín transformation story", "Tayrona National Park", "Amazon birding"],
    experiences: ["Culture", "Food", "Nature", "History", "Adventure"],
    duration: "10–14 days",
    bestTime: "December – March & June – August",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Costa Rica",
    slug: "costa-rica",
    continent: "Central America",
    tagline: "Pura Vida — volcanoes, sloths & rainforests",
    description: "Costa Rica coined 'ecotourism' — and with good reason. Cloud forests, active volcanoes, surf beaches, and an astonishing density of wildlife (5% of Earth's biodiversity) all coexist in this tiny, peaceful nation. 365 Tours builds intimate nature-first itineraries here.",
    highlights: ["Monteverde Cloud Forest", "Arenal Volcano zipline", "Manuel Antonio wildlife", "Tortuguero sea turtles", "Corcovado jungle immersion"],
    experiences: ["Nature", "Wildlife", "Adventure", "Beach"],
    duration: "10–14 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Croatia",
    slug: "croatia",
    continent: "Europe",
    tagline: "Dubrovnik's walls, islands & Adriatic blue",
    description: "Croatia's Adriatic coastline is one of Europe's most beautiful — 1,200 islands, medieval walled cities, cascading waterfalls, and crystal-clear turquoise water. 365 Tours designs private island-hopping and coastal road trip itineraries across this stunning country.",
    highlights: ["Dubrovnik Old Town walls", "Plitvice Lakes waterfalls", "Hvar island nightlife", "Diocletian's Palace, Split", "Sailing the Dalmatian coast"],
    experiences: ["Culture", "Beach", "History", "Nature", "Romance"],
    duration: "10–14 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1555990793-da11153b2473?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555990793-da11153b2473?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cuba",
    slug: "cuba",
    continent: "Caribbean",
    tagline: "Vintage Havana, salsa & Caribbean beaches",
    description: "Cuba is frozen in a beautiful time — 1950s American cars cruising Malecón, colonial plazas alive with salsa, crumbling but glorious Havana mansions, and Caribbean beaches at Varadero. 365 Tours crafts private cultural immersions before Cuba changes further.",
    highlights: ["Havana Old Town", "Trinidad colonial streets", "Vinales Valley tobacco farms", "Varadero beaches", "Classic car tour"],
    experiences: ["Culture", "History", "Beach", "Food"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cyprus",
    slug: "cyprus",
    continent: "Europe",
    tagline: "Aphrodite's island — beaches & Byzantine heritage",
    description: "Cyprus offers Mediterranean charm in compact form — Aphrodite's birthplace, Crusader castles, mosaics from the Roman era, mountain villages producing Commandaria wine, and warm beaches on both coasts. An intimate private tour destination.",
    highlights: ["Paphos Archaeological Park", "Troodos Mountain monasteries", "Famagusta walled city", "Aphrodite's Rock", "Akamas Peninsula"],
    experiences: ["History", "Culture", "Beach", "Nature"],
    duration: "7–10 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1558642084-fd07fae5282e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558642084-fd07fae5282e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Czech Republic",
    slug: "czech-republic",
    continent: "Europe",
    tagline: "Prague's fairy-tale spires & Bohemian castles",
    description: "The Czech Republic is Central Europe's crown jewel — Prague's Gothic spires and Art Nouveau cafés, medieval Ceský Krumlov, the spa town of Karlovy Vary, and Bohemian wine country. 365 Tours builds deeply cultural private itineraries through this beautiful country.",
    highlights: ["Prague Old Town Square", "Charles Bridge at dawn", "Ceský Krumlov castle", "Kutná Hora Bone Church", "Bohemian wineries"],
    experiences: ["History", "Culture", "Food", "Romance"],
    duration: "8–12 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Dubai",
    slug: "dubai",
    continent: "Middle East",
    tagline: "Ultramodern skylines meet ancient desert culture",
    description: "Dubai is the world's most ambitious city — the world's tallest building, islands shaped like palm trees, souks full of gold and spices, and desert dunes just 30 minutes from the Burj Khalifa. 365 Tours combines the best of modern Dubai with authentic Emirati culture.",
    highlights: ["Burj Khalifa observation deck", "Desert safari & BBQ", "Gold & Spice Souk", "Dubai Frame", "Abra ride in Dubai Creek"],
    experiences: ["Luxury", "Culture", "Adventure", "Food"],
    duration: "5–8 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ecuador",
    slug: "ecuador",
    continent: "South America",
    tagline: "Galápagos, cloud forests & the equator",
    description: "Ecuador is a small country with enormous natural diversity — the Galápagos Islands (Darwin's living laboratory), Amazonian jungle lodges, Andean volcano trekking, and colonial Quito. 365 Tours designs private multi-region journeys across Ecuador's remarkable ecosystems.",
    highlights: ["Galápagos giant tortoises", "Amazon jungle overnight", "Avenue of Volcanoes", "Quito Old Town (UNESCO)", "Otavalo indigenous market"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "12–16 days",
    bestTime: "June – September",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Egypt",
    slug: "egypt",
    continent: "Africa",
    tagline: "Pyramids, pharaohs & Nile river journeys",
    description: "Egypt is the cradle of civilisation — the Great Pyramids of Giza, the Valley of the Kings, Luxor's temple complexes, and a Nile cruise connecting them all. 365 Tours designs private Egyptology tours with expert Egyptologist guides and exclusive after-hours temple access.",
    highlights: ["Great Pyramids & Sphinx", "Valley of the Kings", "Luxor Temple by night", "Nile felucca sunset cruise", "Abu Simbel temples"],
    experiences: ["History", "Culture", "Luxury", "Adventure"],
    duration: "10–14 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1539768942893-daf53e448371?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1539768942893-daf53e448371?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Estonia",
    slug: "estonia",
    continent: "Europe",
    tagline: "Medieval Tallinn & Baltic island escapes",
    description: "Estonia punches far above its size — Tallinn's UNESCO-listed medieval old town is one of Europe's best preserved, the island of Saaremaa has windmills and manor houses, and the country's digital-first culture is unlike anywhere else. A refreshing, uncrowded European gem.",
    highlights: ["Tallinn Old Town ramparts", "Lahemaa National Park", "Saaremaa island", "Open Air Museum", "Pärnu beach resort"],
    experiences: ["History", "Culture", "Nature"],
    duration: "6–9 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1564594985645-4427056e22e2?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1564594985645-4427056e22e2?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ethiopia",
    slug: "ethiopia",
    continent: "Africa",
    tagline: "Rock-hewn churches, ancient empires & the Rift Valley",
    description: "Ethiopia is Africa's most historically rich country — the rock-hewn churches of Lalibela, the ancient obelisks of Aksum, the Blue Nile Falls, Simien Mountains trekking, and the tribal cultures of the Omo Valley. An extraordinary, deeply rewarding private tour destination.",
    highlights: ["Lalibela rock-hewn churches", "Simien Mountains trekking", "Omo Valley tribes", "Aksum obelisks", "Danakil Depression"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "12–18 days",
    bestTime: "October – May",
    image: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Finland",
    slug: "finland",
    continent: "Europe",
    tagline: "Northern lights, saunas & reindeer sleighs",
    description: "Finland is where the Northern Lights dance over frozen lakes, reindeer pull sleighs through snowy Lapland forests, and world-class design meets pristine wilderness. Summer brings the Midnight Sun, with kayaking and island-hopping in the Finnish archipelago.",
    highlights: ["Aurora Borealis in Lapland", "Santa Claus Village, Rovaniemi", "Helsinki Design District", "Finnish lakeland sauna", "Husky safari"],
    experiences: ["Nature", "Adventure", "Culture", "Luxury"],
    duration: "8–12 days",
    bestTime: "December – March (Aurora) | June – August (Midnight Sun)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "France",
    slug: "france",
    continent: "Europe",
    tagline: "Paris, Provence & the French Riviera",
    description: "France is the world's most visited country for good reason — the Eiffel Tower and the Louvre in Paris, lavender fields in Provence, châteaux along the Loire Valley, the Riviera glamour of Nice and Monaco, and some of the world's greatest food and wine. 365 Tours makes it perfectly personal.",
    highlights: ["Eiffel Tower & Louvre, Paris", "Provence lavender fields", "Loire Valley châteaux", "French Riviera coastline", "Burgundy wine tasting"],
    experiences: ["Culture", "Food", "Romance", "History", "Luxury"],
    duration: "10–16 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Georgia",
    slug: "georgia",
    continent: "Asia",
    tagline: "Caucasus towers, ancient wine & mountain villages",
    description: "Georgia is the world's oldest wine country and one of its most dramatic landscapes — Svaneti's medieval towers, Kazbegi's snow-capped peaks, the cave city of Uplistsikhe, and Tbilisi's art nouveau old town. 365 Tours builds private Caucasus journeys through this hidden gem.",
    highlights: ["Gergeti Trinity Church, Kazbegi", "Svaneti towers", "Tbilisi Old Town", "Uplistsikhe cave city", "Georgian wine tasting in Kakheti"],
    experiences: ["Culture", "History", "Nature", "Food", "Adventure"],
    duration: "8–12 days",
    bestTime: "May – June & September – October",
    image: "https://images.unsplash.com/photo-1562978559-3e3a8d9b4a3a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1562978559-3e3a8d9b4a3a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Germany",
    slug: "germany",
    continent: "Europe",
    tagline: "Castles, Christmas markets & Bavarian culture",
    description: "Germany blends fairytale romance with modern dynamism — Neuschwanstein Castle, the Romantic Road, Berlin's raw creative energy, Black Forest villages, and Munich's Oktoberfest. 365 Tours designs private road trips through Germany's many distinct regions.",
    highlights: ["Neuschwanstein Castle", "Berlin Wall & Brandenburg Gate", "Black Forest drive", "Cologne Cathedral", "Bavarian Alps"],
    experiences: ["History", "Culture", "Nature", "Food"],
    duration: "10–14 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Greece",
    slug: "greece",
    continent: "Europe",
    tagline: "Santorini sunsets, ancient ruins & island life",
    description: "Greece is the birthplace of Western civilisation and one of the Mediterranean's most beautiful destinations — the Acropolis in Athens, the whitewashed villages of Santorini, the medieval streets of Rhodes, and the crystal Ionian waters. A perennial 365 Tours favourite.",
    highlights: ["Santorini caldera sunset", "Acropolis & Parthenon, Athens", "Delphi Oracle ruins", "Mykonos island town", "Meteora monasteries"],
    experiences: ["History", "Culture", "Beach", "Food", "Romance"],
    duration: "10–14 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Guatemala",
    slug: "guatemala",
    continent: "Central America",
    tagline: "Mayan pyramids, Lake Atitlán & volcanoes",
    description: "Guatemala is Central America's most culturally rich destination — Tikal's soaring jungle pyramids, the colonial grandeur of Antigua, the volcanic caldera of Lake Atitlán and its Mayan market villages, and the chance to witness living Mayan traditions. Remarkable private tour material.",
    highlights: ["Tikal ruins at sunrise", "Lake Atitlán by boat", "Antigua colonial streets", "Acatenango Volcano hike", "Chichicastenango market"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1591703823184-53f23cbc8f90?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1591703823184-53f23cbc8f90?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Hungary",
    slug: "hungary",
    continent: "Europe",
    tagline: "Budapest's baths, Danube & Great Plains",
    description: "Hungary's capital Budapest is arguably Europe's most beautiful city — twin cities Buda and Pest straddling the Danube, with thermal baths, Art Nouveau cafés, and ruin bars. Beyond Budapest, the Tokay wine region and Hungarian Plains await private exploration.",
    highlights: ["Budapest Parliament building", "Széchenyi thermal baths", "Fisherman's Bastion sunset", "Ruin bars of Pest", "Eger wine caves"],
    experiences: ["Culture", "History", "Food", "Romance"],
    duration: "7–10 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1549916919-ac57e70f8b67?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1549916919-ac57e70f8b67?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Iceland",
    slug: "iceland",
    continent: "Europe",
    tagline: "Northern lights, geysers & midnight sun",
    description: "Iceland is pure elemental drama — erupting geysers, thundering waterfalls, black sand beaches, glacier lagoons, and the Northern Lights dancing overhead in winter. In summer the Midnight Sun makes it a photographer's dream. 365 Tours designs Ring Road road trips with private guides.",
    highlights: ["Golden Circle (Geysir, Gullfoss)", "Northern Lights hunting", "Blue Lagoon geothermal spa", "Jökulsárlón glacier lagoon", "Snæfellsnes Peninsula"],
    experiences: ["Nature", "Adventure", "Luxury", "Romance"],
    duration: "8–12 days",
    bestTime: "June – August (Midnight Sun) | September – March (Aurora)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Indonesia",
    slug: "indonesia",
    continent: "Asia",
    tagline: "Bali temples, Komodo dragons & Raja Ampat reefs",
    description: "Indonesia spans 17,000 islands — Bali's Hindu temples and rice terraces, Komodo's prehistoric dragons, Raja Ampat's world-best diving, Borobudur's Buddhist stupas, and Java's volcanic highlands. 365 Tours multi-island itineraries reveal Indonesia's astonishing breadth.",
    highlights: ["Borobudur sunrise", "Komodo dragon tracking", "Bali rice terrace walk", "Raja Ampat diving", "Yogyakarta batik tradition"],
    experiences: ["Culture", "Nature", "Adventure", "Beach", "Wildlife"],
    duration: "14–21 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Iran",
    slug: "iran",
    continent: "Asia",
    tagline: "Persian empire, blue mosques & ancient bazaars",
    description: "Iran is one of the world's most surprising and rewarding travel destinations — the turquoise-tiled mosques of Isfahan, Persepolis' Achaemenid ruins, the pink salt lake of Maharloo, and Iran's legendary hospitality. 365 Tours crafts carefully planned private cultural tours.",
    highlights: ["Nasir al-Mulk Mosque, Shiraz", "Persepolis ruins", "Naqsh-e Jahan Square, Isfahan", "Golestan Palace, Tehran", "Kashan historic houses"],
    experiences: ["History", "Culture"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Israel",
    slug: "israel",
    continent: "Middle East",
    tagline: "Jerusalem's old city, Dead Sea & Tel Aviv beaches",
    description: "Israel packs millennia of history and remarkable diversity into a tiny country — Jerusalem's Old City with the Western Wall and Church of the Holy Sepulchre, the Dead Sea, Masada's fortress, Tel Aviv's beaches, and the Negev Desert. A deeply moving private tour destination.",
    highlights: ["Jerusalem Old City & Western Wall", "Dead Sea float", "Masada sunrise cable car", "Tel Aviv Carmel Market", "Petra (Jordan) day trip"],
    experiences: ["History", "Culture", "Beach", "Adventure"],
    duration: "8–12 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Italy",
    slug: "italy",
    continent: "Europe",
    tagline: "Rome, Renaissance & la dolce vita",
    description: "Italy has more UNESCO World Heritage Sites than any other country — the Colosseum in Rome, the canals of Venice, the Uffizi in Florence, the Amalfi Coast, and Sicily's Greek temples. 365 Tours designs private cultural road trips through Italy's inexhaustible riches.",
    highlights: ["Colosseum & Vatican, Rome", "Gondola in Venice", "Uffizi Gallery, Florence", "Amalfi Coast drive", "Trulli houses, Alberobello"],
    experiences: ["History", "Culture", "Food", "Romance", "Luxury"],
    duration: "12–18 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Japan",
    slug: "japan",
    continent: "Asia",
    tagline: "Cherry blossoms, temples & neon modernity",
    description: "Japan is a country of thrilling contrasts — ancient Shinto shrines and neon-lit Tokyo skyscrapers, Kyoto's geisha districts and bullet trains, cherry blossoms over Hiroshima's Peace Park, and the powder snow of Hokkaido. 365 Tours navigates Japan's complexity with private expertise.",
    highlights: ["Fushimi Inari torii gates", "Tokyo shibuya crossing", "Hiroshima Peace Memorial", "Arashiyama bamboo grove", "Mt. Fuji view from Hakone"],
    experiences: ["Culture", "History", "Food", "Nature", "Luxury"],
    duration: "12–18 days",
    bestTime: "March – May (Cherry Blossom) | November – December (Autumn)",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Jordan",
    slug: "jordan",
    continent: "Middle East",
    tagline: "Petra's rose-red city & Wadi Rum desert",
    description: "Jordan is one of the Middle East's most rewarding destinations — Petra's rose-red Nabataean city carved into cliff faces, Wadi Rum's vast desert landscapes, the Roman ruins of Jerash, the Dead Sea, and Aqaba's Red Sea reefs. Compact and deeply impactful.",
    highlights: ["Petra Treasury at sunrise", "Wadi Rum jeep & camp", "Dead Sea float", "Jerash Roman ruins", "Aqaba snorkelling"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "7–10 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Kenya",
    slug: "kenya",
    continent: "Africa",
    tagline: "Masai Mara, Great Migration & Swahili coast",
    description: "Kenya is Africa's safari capital — the Masai Mara hosts the world's greatest wildlife spectacle, the Great Migration, while Amboseli offers elephant herds with Kilimanjaro as backdrop. The Swahili coast of Lamu adds ancient culture and white sand beaches. A world-class destination.",
    highlights: ["Great Migration, Masai Mara", "Amboseli elephant herds", "Lamu Old Town", "Mount Kenya trekking", "Giraffe Centre, Nairobi"],
    experiences: ["Wildlife", "Nature", "Culture", "Adventure", "Luxury"],
    duration: "10–16 days",
    bestTime: "July – October (Migration) | January – February",
    image: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Laos",
    slug: "laos",
    continent: "Asia",
    tagline: "Luang Prabang monks, Mekong & 4000 Islands",
    description: "Laos is South East Asia's most serene country — Luang Prabang's saffron-robed monks at dawn, the Kuang Si turquoise waterfalls, slow-boat journeys on the Mekong, and the tranquil 4000 Islands in the south. Perfect for a slow, contemplative private journey.",
    highlights: ["Alms-giving ceremony, Luang Prabang", "Kuang Si Falls", "Plain of Jars", "Mekong slow boat", "Si Phan Don (4000 Islands)"],
    experiences: ["Culture", "Nature", "History", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – February",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Latvia",
    slug: "latvia",
    continent: "Europe",
    tagline: "Art Nouveau Riga & Baltic forests",
    description: "Latvia's capital Riga has the largest collection of Art Nouveau architecture in the world, alongside a thriving food and design scene. The country's national parks, singing festival tradition, and medieval Gauja Valley castles make it a rewarding Baltic private tour.",
    highlights: ["Riga Old Town", "Art Nouveau district walk", "Gauja National Park", "Jurmala beach resort", "Turaida Castle"],
    experiences: ["Culture", "History", "Nature"],
    duration: "6–8 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Lithuania",
    slug: "lithuania",
    continent: "Europe",
    tagline: "Baroque Vilnius, the Hill of Crosses & Baltic coast",
    description: "Lithuania's Vilnius is one of Europe's most beautiful Baroque capitals — a UNESCO-listed Old Town, the Republic of Uzupis artist enclave, and an extraordinary Jewish heritage. The Hill of Crosses and the Curonian Spit UNESCO dunes add remarkable variety.",
    highlights: ["Vilnius Old Town", "Hill of Crosses", "Curonian Spit sand dunes", "Trakai Island Castle", "Palanga amber museum"],
    experiences: ["History", "Culture", "Nature"],
    duration: "6–8 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Macau",
    slug: "macau",
    continent: "Asia",
    tagline: "Portuguese heritage meets Chinese gaming capital",
    description: "Macau blends 400 years of Portuguese colonial history with Chinese culture in a tiny peninsula — Baroque churches, Chinese temples, and the Cotai entertainment strip. Perfect as a short private cultural break or combined with a Hong Kong itinerary.",
    highlights: ["Ruins of St. Paul's", "Senado Square", "Taipa Village", "Macau Tower bungee", "A-Ma Temple"],
    experiences: ["History", "Culture", "Food"],
    duration: "3–5 days",
    bestTime: "October – December",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Madagascar",
    slug: "madagascar",
    continent: "Africa",
    tagline: "Lemurs, baobab avenues & otherworldly nature",
    description: "Madagascar is one of the world's greatest biodiversity hotspots — 90% of its wildlife exists nowhere else on Earth. Ring-tailed lemurs, the Avenue of Baobabs at sunset, tsingy limestone formations, and whale watching in Sainte Marie make this a truly unique private tour.",
    highlights: ["Avenue of Baobabs, Morondava", "Lemur sightings, Ranomafana", "Tsingy de Bemaraha", "Whale watching, Ile Sainte-Marie", "Nosy Be beaches"],
    experiences: ["Wildlife", "Nature", "Adventure", "Beach"],
    duration: "14–18 days",
    bestTime: "April – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Malawi",
    slug: "malawi",
    continent: "Africa",
    tagline: "The warm heart of Africa & Lake Malawi",
    description: "Known as 'The Warm Heart of Africa' for the friendliness of its people, Malawi offers Lake Malawi's crystal waters, Liwonde National Park's elephants, and Nyika Plateau's rolling highlands. A genuinely off-the-beaten-path African private tour destination.",
    highlights: ["Lake Malawi kayaking", "Liwonde National Park boat safari", "Nyika Plateau hiking", "Livingstonia Mission", "Cape Maclear snorkelling"],
    experiences: ["Wildlife", "Nature", "Adventure", "Beach"],
    duration: "10–14 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Malaysia",
    slug: "malaysia",
    continent: "Asia",
    tagline: "Rainforests, orangutans & Petronas Towers",
    description: "Malaysia effortlessly blends jungle and city — Kuala Lumpur's Petronas Towers, the ancient rainforests of Borneo with wild orangutans, the cave temples of Batu Caves, and the gorgeous Perhentian islands. A wonderful multi-region private tour destination.",
    highlights: ["Orangutan spotting, Borneo", "Petronas Twin Towers, KL", "Penang street food", "Perhentian Islands diving", "Cameron Highlands tea estates"],
    experiences: ["Wildlife", "Culture", "Nature", "Food", "Beach"],
    duration: "12–16 days",
    bestTime: "December – February",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Maldives",
    slug: "maldives",
    continent: "Asia",
    tagline: "Overwater villas & Indian Ocean reefs",
    description: "The Maldives is the world's quintessential luxury beach destination — 1,000+ coral islands in the Indian Ocean, where overwater bungalows sit above turquoise lagoons and vibrant coral reefs teem with manta rays and whale sharks. 365 Tours selects the finest private island resorts.",
    highlights: ["Overwater villa sunrise", "Manta ray snorkelling", "Whale shark dive", "Private sandbank picnic", "Sunset dolphin cruise"],
    experiences: ["Beach", "Luxury", "Romance", "Nature"],
    duration: "6–10 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mauritius",
    slug: "mauritius",
    continent: "Africa",
    tagline: "Turquoise lagoons, creole culture & luxury resorts",
    description: "Mauritius is a gem in the Indian Ocean — white sand beaches, turquoise lagoons perfect for water sports, vibrant Creole markets, the dramatic Black River Gorges, and some of the world's finest luxury beach resorts. 365 Tours pairs resort stays with authentic island exploration.",
    highlights: ["Blue Bay Marine Park snorkelling", "Black River Gorges hike", "Chamarel Coloured Earths", "Port Louis market", "Ile aux Cerfs lagoon"],
    experiences: ["Beach", "Luxury", "Romance", "Nature", "Culture"],
    duration: "8–12 days",
    bestTime: "May – December",
    image: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mexico",
    slug: "mexico",
    continent: "North America",
    tagline: "Mayan pyramids, Day of the Dead & Pacific beaches",
    description: "Mexico is a continent-sized cultural experience — Chichén Itzá's pyramid, Mexico City's baroque cathedrals and world-class museums, Oaxaca's mole and mezcal, the Yucatán cenotes, and Cabo's Pacific beaches. 365 Tours designs rich private cultural itineraries across this vast country.",
    highlights: ["Chichén Itzá Pyramid", "Mexico City's Frida Kahlo Museum", "Cenote swimming, Yucatán", "Oaxaca food trail", "Monarch butterfly migration"],
    experiences: ["History", "Culture", "Food", "Nature", "Beach"],
    duration: "12–18 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1535818860179-a85038b51b15?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1535818860179-a85038b51b15?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mongolia",
    slug: "mongolia",
    continent: "Asia",
    tagline: "Gobi Desert, nomad stays & the Naadam Festival",
    description: "Mongolia is one of the world's last great wildernesses — the vast Gobi Desert, the rolling steppe under limitless sky, the ancient capital Karakorum, and the chance to stay in a nomadic family's ger and ride horses across the grasslands. A transformative private journey.",
    highlights: ["Naadam Festival (July)", "Gobi Desert camel trek", "Ger camp homestay", "Terelj National Park", "Karakorum monastery"],
    experiences: ["Culture", "Adventure", "Nature", "Wildlife"],
    duration: "10–16 days",
    bestTime: "June – September",
    image: "https://images.unsplash.com/photo-1536329583941-14287ec6fc4e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1536329583941-14287ec6fc4e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Morocco",
    slug: "morocco",
    continent: "Africa",
    tagline: "Sahara dunes, medinas & Atlas Mountains",
    description: "Morocco is a feast for all senses — the labyrinthine souks of Fez, Sahara dunes at Erg Chebbi, the blue city of Chefchaouen, Marrakech's Jemaa el-Fna square, and mountain Berber villages in the High Atlas. 365 Tours designs private Imperial Cities tours and Sahara expeditions.",
    highlights: ["Sahara camel trek, Merzouga", "Fez medina walk", "Chefchaouen blue streets", "Marrakech souks", "High Atlas Berber village"],
    experiences: ["Culture", "History", "Adventure", "Food", "Nature"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mozambique",
    slug: "mozambique",
    continent: "Africa",
    tagline: "Bazaruto Archipelago & Portuguese colonial charm",
    description: "Mozambique is Africa's most beautiful coastline — the Bazaruto Archipelago's whale sharks and dugongs, the Portuguese colonial elegance of Mozambique Island, and the laid-back Tofo beach surf culture. 365 Tours pairs wilderness coast with authentic culture in this undiscovered gem.",
    highlights: ["Bazaruto Archipelago islands", "Whale shark snorkelling, Tofo", "Mozambique Island (UNESCO)", "Gorongosa National Park", "Pemba coastline"],
    experiences: ["Beach", "Wildlife", "Culture", "Adventure"],
    duration: "10–14 days",
    bestTime: "May – November",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Myanmar",
    slug: "myanmar",
    continent: "Asia",
    tagline: "Bagan's pagodas, Inle Lake & golden temples",
    description: "Myanmar's ancient Buddhist culture remains one of South East Asia's most authentic — the 2,000 pagodas of Bagan at sunrise, fishermen casting nets on Inle Lake, the golden Shwedagon Pagoda in Yangon, and the hill tribes of Shan State. A private tour of rare beauty.",
    highlights: ["Bagan pagoda sunrise balloon", "Inle Lake leg-rowing fishermen", "Shwedagon Pagoda, Yangon", "Mandalay Palace", "Kyaiktiyo Golden Rock"],
    experiences: ["Culture", "History", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – February",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Namibia",
    slug: "namibia",
    continent: "Africa",
    tagline: "Sossusvlei dunes, Etosha & the Skeleton Coast",
    description: "Namibia is Africa's most dramatic landscape — the burnt-orange Sossusvlei dunes towering over white salt pans, Etosha's vast salt pan teeming with wildlife, the ghostly Skeleton Coast shipwrecks, and the Himba people of Kaokoland. Extraordinary private safari territory.",
    highlights: ["Sossusvlei dunes & Deadvlei", "Etosha lion & elephant", "Skeleton Coast drive", "Fish River Canyon hike", "Himba village visit"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "12–16 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Nepal",
    slug: "nepal",
    continent: "Asia",
    tagline: "Everest base camp, Himalayan kingdoms & Buddhist monasteries",
    description: "Nepal is the ultimate Himalayan destination — Everest Base Camp treks, Annapurna Circuit, Kathmandu's ancient temples and palaces, the jungle of Chitwan for wildlife, and the medieval city of Bhaktapur. 365 Tours builds private Himalayan journeys at every level of adventure.",
    highlights: ["Everest Base Camp trek", "Annapurna panorama", "Kathmandu Durbar Square", "Chitwan rhino & elephant", "Pokhara lakeside sunrise"],
    experiences: ["Adventure", "Nature", "Culture", "History", "Wildlife"],
    duration: "12–18 days",
    bestTime: "October – November & March – May",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Netherlands",
    slug: "netherlands",
    continent: "Europe",
    tagline: "Tulip fields, windmills & Golden Age canals",
    description: "The Netherlands is compact, beautiful, and cycling-friendly — Amsterdam's canal ring and world-class museums, Keukenhof's tulip fields in spring, Vermeer's Delft, windmills at Kinderdijk, and the vibrant Hague. 365 Tours builds private, unhurried Dutch itineraries.",
    highlights: ["Keukenhof tulip fields (April)", "Amsterdam canal evening", "Rijksmuseum & Van Gogh Museum", "Windmills at Kinderdijk", "Delft blue pottery workshop"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "7–10 days",
    bestTime: "April – May & September",
    image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "New Zealand",
    slug: "new-zealand",
    continent: "Oceania",
    tagline: "Fiordland, Hobbiton & Maori culture",
    description: "New Zealand's landscapes seem designed for cinema — Milford Sound's fiords, the geothermal wonders of Rotorua, the Hobbiton movie set, Queenstown's adventure sports, and the Maori cultural heartland of Northland. 365 Tours crafts private North Island and South Island journeys.",
    highlights: ["Milford Sound cruise", "Hobbiton movie set", "Rotorua geothermal & Maori culture", "Queenstown bungy & adventure", "Abel Tasman sea kayak"],
    experiences: ["Nature", "Adventure", "Culture", "Wildlife", "Luxury"],
    duration: "14–21 days",
    bestTime: "December – March (South) | October – April (North)",
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Nicaragua",
    slug: "nicaragua",
    continent: "Central America",
    tagline: "Volcanoes, colonial cities & surf beaches",
    description: "Nicaragua is Central America's most rewarding undiscovered destination — the colonial cities of Granada and León, volcano boarding on Cerro Negro, the twin-lake island of Ometepe, and Pacific surf beaches at San Juan del Sur. An authentic private adventure.",
    highlights: ["Granada colonial centre", "Volcano boarding, Cerro Negro", "Ometepe Island cycling", "León cathedral views", "San Juan del Sur beaches"],
    experiences: ["Adventure", "Culture", "Beach", "Nature"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Norway",
    slug: "norway",
    continent: "Europe",
    tagline: "Fjords, Northern lights & Viking heritage",
    description: "Norway's fjords are among the most awe-inspiring landscapes on Earth — Geirangerfjord's cascading waterfalls, the Lofoten Islands' dramatic peaks, the Northern Lights over Tromsø, and the Viking Ship Museum in Oslo. 365 Tours designs private coastal Norway journeys by ship and road.",
    highlights: ["Geirangerfjord cruise", "Lofoten Islands drive", "Northern Lights, Tromsø", "Flåm Railway", "Bergen fish market"],
    experiences: ["Nature", "Adventure", "Culture", "History"],
    duration: "10–14 days",
    bestTime: "June – August (Fjords) | October – March (Aurora)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Oman",
    slug: "oman",
    continent: "Middle East",
    tagline: "Wadis, desert forts & the Arabian Sea",
    description: "Oman is the Gulf's most authentically Arabian destination — ancient forts across the Hajar Mountains, turquoise wadis for swimming, the Wahiba Sands for overnight desert camps, and Muscat's magnificent Sultan Qaboos Mosque. 365 Tours offers private cultural immersions unlike any other Gulf destination.",
    highlights: ["Sultan Qaboos Grand Mosque", "Wadi Shab swimming", "Wahiba Sands desert camp", "Nizwa Fort & souk", "Mutrah Corniche"],
    experiences: ["Culture", "History", "Adventure", "Nature", "Luxury"],
    duration: "8–12 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Panama",
    slug: "panama",
    continent: "Central America",
    tagline: "The Canal, San Blas islands & cloud forests",
    description: "Panama is far more than its famous canal — the indigenous San Blas Archipelago with its Kuna Yala communities, the cloud forests of Boquete, the pre-Columbian heritage of Panamá Viejo, and a capital city of surprising sophistication. A rewarding private tour destination.",
    highlights: ["Panama Canal Miraflores locks", "San Blas island community stay", "Boquete cloud forest hike", "Panama City Old Quarter", "Chiriqui River white water"],
    experiences: ["Culture", "Nature", "Adventure", "History", "Beach"],
    duration: "10–14 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Paraguay",
    slug: "paraguay",
    continent: "South America",
    tagline: "Jesuit missions, wetlands & Guaraní culture",
    description: "Paraguay is South America's most overlooked destination — the UNESCO Jesuit Missions of Trinidad and Jesús, the Chaco wilderness with its extraordinary wildlife, the Iguazu Falls nearby, and the Guaraní cultural heartland of Asunción. A private tour with genuine discovery.",
    highlights: ["Jesuit Missions of Trinidad", "Pantanal wetland wildlife", "Asunción historic centre", "Ybycuí National Park", "Rio Paraguay boat trip"],
    experiences: ["History", "Culture", "Wildlife", "Nature"],
    duration: "8–12 days",
    bestTime: "April – September",
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Peru",
    slug: "peru",
    continent: "South America",
    tagline: "Machu Picchu, Inca trails & Amazon headwaters",
    description: "Peru is South America's most captivating destination — Machu Picchu rising from Andean mist, the Sacred Valley of the Incas, the floating reed islands of Lake Titicaca, the Amazon jungle from Iquitos, and Lima's world-class gastronomy. An extraordinary private itinerary.",
    highlights: ["Machu Picchu sunrise", "Sacred Valley of the Incas", "Lake Titicaca reed islands", "Amazon jungle lodge, Iquitos", "Lima food trail"],
    experiences: ["History", "Culture", "Adventure", "Nature", "Food"],
    duration: "12–18 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Philippines",
    slug: "philippines",
    continent: "Asia",
    tagline: "7,000+ islands, chocolate hills & whale sharks",
    description: "The Philippines is a 7,000-island archipelago of extraordinary diversity — the Chocolate Hills of Bohol, whale shark encounters in Oslob, rice terraces carved 2,000 years ago in Banaue, the party islands of Boracay, and the underground river of Palawan. 365 Tours designs private island-hopping adventures.",
    highlights: ["El Nido island hopping, Palawan", "Chocolate Hills, Bohol", "Whale shark swim, Cebu", "Banaue rice terraces", "Boracay White Beach"],
    experiences: ["Beach", "Nature", "Adventure", "Culture", "Wildlife"],
    duration: "12–18 days",
    bestTime: "November – May",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Poland",
    slug: "poland",
    continent: "Europe",
    tagline: "Kraków's old town, Auschwitz & Tatra mountains",
    description: "Poland's depth of history is extraordinary — Kraków's Royal Castle and Jewish Quarter, the solemnity of Auschwitz-Birkenau, Warsaw's rebuilt Old Town, the fairy-tale Malbork Castle, and the Tatra Mountains for hiking. An emotionally powerful private tour destination.",
    highlights: ["Kraków Old Town & Wawel", "Auschwitz-Birkenau memorial", "Warsaw Royal Route", "Wieliczka Salt Mine", "Tatra Mountains hiking"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "8–12 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1562874702-3f08a9a99d55?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1562874702-3f08a9a99d55?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Portugal",
    slug: "portugal",
    continent: "Europe",
    tagline: "Lisbon trams, Douro wine & Algarve cliffs",
    description: "Portugal is Western Europe's warmest and most soulful country — Lisbon's hilly neighbourhoods and fado music, the wine terraces of the Douro Valley, the romantic palaces of Sintra, and the golden cliffs of the Algarve. 365 Tours designs private itineraries through all of Portugal's chapters.",
    highlights: ["Lisbon tram & Belém Tower", "Douro Valley wine cruise", "Sintra romantic palaces", "Algarve sea cave kayak", "Porto ribeira riverside"],
    experiences: ["Culture", "Food", "Nature", "History", "Romance"],
    duration: "10–14 days",
    bestTime: "March – October",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Russia",
    slug: "russia",
    continent: "Europe",
    tagline: "Moscow's Kremlin, Trans-Siberian & Lake Baikal",
    description: "Russia's scale is incomprehensible — the Kremlin and Red Square in Moscow, the palaces and canals of St. Petersburg, the Trans-Siberian Railway crossing eleven time zones, and the world's deepest lake at Baikal. 365 Tours designs private cultural expeditions across Russia's vast history.",
    highlights: ["Red Square & Kremlin, Moscow", "Hermitage Museum, St. Petersburg", "Trans-Siberian Railway", "Lake Baikal ice trek", "Bolshoi Theatre performance"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "14–21 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Serbia",
    slug: "serbia",
    continent: "Europe",
    tagline: "Belgrade nightlife, monasteries & Danube gorges",
    description: "Serbia is the Balkans' most exciting emerging destination — Belgrade's legendary nightlife on the Sava and Danube rivers, medieval monasteries in the countryside, the Iron Gates gorge on the Danube, and the bohemian Skadarlija quarter. A genuinely surprising private tour.",
    highlights: ["Belgrade fortress & Kalemegdan", "Drvengrad village (Kusturica)", "Iron Gates gorge cruise", "Studenica Monastery", "Novi Sad Petrovaradin fortress"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "7–10 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Seychelles",
    slug: "seychelles",
    continent: "Africa",
    tagline: "Giant tortoises, pristine beaches & granite boulders",
    description: "The Seychelles is one of the world's most beautiful archipelagos — ancient granite boulders framing powder-white beaches, giant Aldabra tortoises roaming freely, and coral reefs bursting with colour. 365 Tours selects the finest island resorts for an intimate private escape.",
    highlights: ["Anse Source d'Argent, La Digue", "Giant tortoise sanctuary", "Vallée de Mai palm forest (UNESCO)", "Beau Vallon beach, Mahé", "Snorkelling off St. Anne"],
    experiences: ["Beach", "Luxury", "Romance", "Nature", "Wildlife"],
    duration: "8–12 days",
    bestTime: "April – May & October – November",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Singapore",
    slug: "singapore",
    continent: "Asia",
    tagline: "Garden city, hawker culture & world-class design",
    description: "Singapore is the world's most efficiently extraordinary city — the Gardens by the Bay supertrees, Hawker Centre cuisine (UNESCO listed), the historic colonial district, Sentosa Island, and the world's best airport as a destination in itself. 365 Tours pairs Singapore with Malaysia or Indonesia for a regional private tour.",
    highlights: ["Gardens by the Bay night show", "Maxwell Hawker Centre food trail", "Marina Bay Sands rooftop", "Chinatown & Little India", "Sentosa island resort"],
    experiences: ["Culture", "Food", "Luxury", "Nature"],
    duration: "5–7 days",
    bestTime: "February – April",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "South Africa",
    slug: "south-africa",
    continent: "Africa",
    tagline: "Big Five safaris, Cape Town & the Garden Route",
    description: "South Africa is the world's most diverse destination in a single country — Kruger National Park's Big Five, Cape Town under Table Mountain, the winelands of Stellenbosch, the Garden Route coastal drive, and the Drakensberg mountains. 365 Tours designs comprehensive private South Africa journeys.",
    highlights: ["Kruger safari game drives", "Table Mountain cable car", "Cape Peninsula drive", "Stellenbosch wine tour", "Drakensberg hike"],
    experiences: ["Wildlife", "Nature", "Culture", "Food", "Adventure", "Luxury"],
    duration: "14–21 days",
    bestTime: "May – September (Safari) | November – March (Cape)",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "South Korea",
    slug: "south-korea",
    continent: "Asia",
    tagline: "K-culture, palace temples & mountain shrines",
    description: "South Korea blends the ultra-modern and the deeply traditional — Seoul's neon-lit streets and Joseon Dynasty palaces, Gyeongju's ancient Silla kingdoms, Jeju Island's volcanic lava tubes, and the Buddhist temple stays of the countryside. 365 Tours builds private K-cultural journeys.",
    highlights: ["Gyeongbokgung Palace in hanbok", "Bukchon Hanok Village, Seoul", "Jeju Island volcanic landscape", "Haeinsa Buddhist temple stay", "DMZ border zone visit"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Spain",
    slug: "spain",
    continent: "Europe",
    tagline: "Gaudí, flamenco, Alhambra & pintxos",
    description: "Spain's richness is extraordinary — the modernist genius of Gaudí's Barcelona, the Moorish grandeur of the Alhambra in Granada, the Prado's masterpieces in Madrid, the pilgrimage routes of Camino de Santiago, and the pintxos bars of San Sebastián. A private Spain tour never disappoints.",
    highlights: ["Sagrada Família & Park Güell", "Alhambra at dusk, Granada", "Prado Museum, Madrid", "San Sebastián food tour", "Flamenco performance, Seville"],
    experiences: ["Culture", "History", "Food", "Romance", "Luxury"],
    duration: "12–16 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Sri Lanka",
    slug: "sri-lanka",
    continent: "Asia",
    tagline: "Sigiriya, tea country & golden beaches",
    description: "Sri Lanka packs extraordinary diversity into a compact island — the ancient Sigiriya rock fortress, the cool tea estates of Nuwara Eliya, Yala National Park's leopards, the golden beaches of the south coast, and the living heritage of Kandy's Temple of the Tooth. 365 Tours' most popular short-haul private tour.",
    highlights: ["Sigiriya rock fortress climb", "Yala leopard safari", "Ella train journey", "Kandy Perahera festival", "Mirissa whale watching"],
    experiences: ["History", "Wildlife", "Nature", "Culture", "Beach"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Sweden",
    slug: "sweden",
    continent: "Europe",
    tagline: "Ice hotels, Midnight Sun & Viking heritage",
    description: "Sweden is Scandinavia's most varied destination — Stockholm's island archipelago and museum island Djurgården, the Icehotel of Jukkasjärvi, the Midnight Sun in Lapland, and the Viking heritage of Gamla Uppsala. 365 Tours designs private Swedish journeys by boat and road.",
    highlights: ["ICEHOTEL, Jukkasjärvi", "Stockholm archipelago boat", "ABBA Museum, Stockholm", "Gamla Uppsala Viking burial mounds", "Midnight Sun in Lapland"],
    experiences: ["Culture", "Adventure", "Nature", "History", "Luxury"],
    duration: "8–12 days",
    bestTime: "June – August (Midnight Sun) | December – March (Aurora)",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Switzerland",
    slug: "switzerland",
    continent: "Europe",
    tagline: "Alpine peaks, chocolate & luxury trains",
    description: "Switzerland is pristine perfection — the Matterhorn reflected in Riffelsee, Interlaken's adventure sports, the Jungfraujoch 'Top of Europe', the Glacier Express train journey, and the luxury hotel culture of Lucerne and Geneva. 365 Tours builds private Swiss Grand Tours in unmatched style.",
    highlights: ["Matterhorn & Zermatt", "Jungfraujoch top of Europe", "Glacier Express train", "Lucerne Chapel Bridge", "Lake Geneva sunset"],
    experiences: ["Nature", "Luxury", "Adventure", "Romance", "Culture"],
    duration: "10–14 days",
    bestTime: "June – September & December – March",
    image: "https://images.unsplash.com/photo-1527434762461-6f0c5c5b4c7e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1527434762461-6f0c5c5b4c7e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tanzania",
    slug: "tanzania",
    continent: "Africa",
    tagline: "Serengeti, Kilimanjaro & Zanzibar beaches",
    description: "Tanzania offers East Africa's greatest safari experience — the vast Serengeti with its Great Migration of 1.5 million wildebeest, Ngorongoro Crater's dense wildlife, the summit of Kilimanjaro for trekkers, and Zanzibar's spice trails and turquoise beaches. An iconic private African journey.",
    highlights: ["Great Migration, Serengeti", "Ngorongoro Crater game drive", "Kilimanjaro summit trek", "Zanzibar Stone Town", "Mahale chimpanzee trek"],
    experiences: ["Wildlife", "Adventure", "Nature", "Beach", "Culture"],
    duration: "14–21 days",
    bestTime: "June – October (Migration) | December – March (Beach)",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Thailand",
    slug: "thailand",
    continent: "Asia",
    tagline: "Temples, floating markets & Andaman islands",
    description: "Thailand is South East Asia's most beloved destination — Bangkok's golden wats and floating markets, Chiang Mai's jungle elephant sanctuaries, the karst limestone of Phang Nga Bay, and the gulf islands of Koh Samui. 365 Tours designs private multi-region Thai journeys of every style.",
    highlights: ["Grand Palace & Wat Phra Kaew", "Chiang Mai elephant sanctuary", "Phang Nga Bay sea kayak", "Floating market, Damnoen Saduak", "Full Moon Party or quiet Koh Lanta"],
    experiences: ["Culture", "Beach", "Nature", "Food", "Adventure"],
    duration: "10–16 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tibet",
    slug: "tibet",
    continent: "Asia",
    tagline: "Potala Palace, monastery stays & the Roof of the World",
    description: "Tibet is one of the world's most spiritually profound destinations — the Potala Palace in Lhasa towering over the plateau, Jokhang Temple's pilgrims prostrating on ancient flagstones, the sacred Lake Namtso, and the Tibetan plateau's sky-scraping landscapes. A deeply moving private tour.",
    highlights: ["Potala Palace, Lhasa", "Jokhang Temple pilgrims", "Lake Namtso at 4,718m", "Monastery of Tashilhunpo", "Everest Base Camp (Tibet side)"],
    experiences: ["Culture", "History", "Adventure", "Nature"],
    duration: "10–14 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tunisia",
    slug: "tunisia",
    continent: "Africa",
    tagline: "Carthage, Sahara villages & Mediterranean beaches",
    description: "Tunisia is North Africa's most accessible and diverse destination — the ancient ruins of Carthage, the Star Wars filming locations of the Sahara, the blue and white hill village of Sidi Bou Saïd, Djerba's Jewish heritage, and Mediterranean beaches. An extraordinary private tour value.",
    highlights: ["Carthage ruins", "Sahara jeep tour", "Sidi Bou Saïd village", "Bardo Museum mosaics", "Djerba island"],
    experiences: ["History", "Culture", "Adventure", "Beach"],
    duration: "8–12 days",
    bestTime: "March – June & September – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Turkey",
    slug: "turkey",
    continent: "Asia",
    tagline: "Cappadocia balloons, Hagia Sophia & turquoise coast",
    description: "Turkey bridges two continents and two civilisations — the Blue Mosque and Grand Bazaar of Istanbul, the fairy-chimney landscape of Cappadocia with hot air balloons at sunrise, the Aegean turquoise coast, and the ancient ruins of Ephesus. 365 Tours designs comprehensive private Turkish itineraries.",
    highlights: ["Hot air balloon, Cappadocia", "Hagia Sophia & Blue Mosque, Istanbul", "Grand Bazaar & Bosphorus cruise", "Ruins of Ephesus", "Turquoise Coast gulet cruise"],
    experiences: ["History", "Culture", "Adventure", "Beach", "Food", "Romance"],
    duration: "10–16 days",
    bestTime: "April – May & September – October",
    image: "https://images.unsplash.com/photo-1545631757-4f36af74c1de?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1545631757-4f36af74c1de?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Uganda",
    slug: "uganda",
    continent: "Africa",
    tagline: "Gorilla trekking, Bwindi & the Nile source",
    description: "Uganda is 'The Pearl of Africa' — mountain gorilla trekking in the Bwindi Impenetrable Forest is the most profound wildlife encounter on Earth, complemented by chimpanzee tracking in Kibale, white-water rafting on the Nile at Jinja, and Queen Elizabeth National Park's tree-climbing lions.",
    highlights: ["Gorilla trekking, Bwindi", "Chimpanzee track, Kibale", "White-water rafting, Nile Jinja", "Tree-climbing lions, Queen Elizabeth NP", "Source of the Nile"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "10–14 days",
    bestTime: "June – September & December – February",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ukraine",
    slug: "ukraine",
    continent: "Europe",
    tagline: "Kyiv's golden domes, Lviv cafés & Carpathians",
    description: "Ukraine is Eastern Europe's largest and most underrated country — Kyiv's golden Orthodox domes and chestnut-lined boulevards, the café culture of Lviv's Austrian heritage old town, the Carpathian ski and hiking highlands, and Odessa's Black Sea promenade. Currently we monitor travel safety conditions closely.",
    highlights: ["Kyiv Pechersk Lavra monastery", "Lviv Old Town & cafés", "Carpathian Mountain hiking", "Chernobyl exclusion zone tour", "Odessa Potemkin Steps"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "United Kingdom",
    slug: "united-kingdom",
    continent: "Europe",
    tagline: "Castles, Highlands & cultural London",
    description: "The United Kingdom packs extraordinary variety — London's world-class museums, the Scottish Highlands and Lochs, the Roman walls of York, Cornwall's coastal footpaths, Oxford and Cambridge's university cities, and the castles of Wales. 365 Tours crafts private British road trip and cultural journeys.",
    highlights: ["Tower of London & Buckingham Palace", "Scottish Highlands & Loch Ness", "Stonehenge at dawn", "Oxford & Blenheim Palace", "Lake District walking"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "12–16 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Uzbekistan",
    slug: "uzbekistan",
    continent: "Asia",
    tagline: "Silk Road cities, turquoise domes & desert caravans",
    description: "Uzbekistan's Silk Road cities are among the most beautiful in the world — the turquoise-tiled Registan in Samarkand, the ancient mudbrick city of Khiva, the madrasas of Bukhara, and the surreal Aral Sea. 365 Tours builds immersive private Silk Road itineraries through this extraordinary country.",
    highlights: ["Registan Square, Samarkand", "Khiva walled city", "Bukhara historic centre", "Aral Sea expedition", "Ferghana Valley silk workshops"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "10–14 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Vietnam",
    slug: "vietnam",
    continent: "Asia",
    tagline: "Ha Long Bay, lantern-lit Hội An & Saigon streets",
    description: "Vietnam stretches 1,650 km from north to south — the emerald bays of Ha Long, the ancient trading port of Hội An glowing with lanterns, the imperial citadel of Huế, the war history of Ho Chi Minh City, and the rice terraces of Sapa. 365 Tours designs private end-to-end Vietnamese journeys.",
    highlights: ["Ha Long Bay cruise", "Hội An lantern night", "Huế Imperial Citadel", "Mỹ Sơn Hindu ruins", "Sapa rice terrace trek"],
    experiences: ["Culture", "History", "Nature", "Food", "Adventure"],
    duration: "12–18 days",
    bestTime: "February – April & August – October",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "West Indies",
    slug: "west-indies",
    continent: "Caribbean",
    tagline: "Cricket, rum, carnival & Caribbean beaches",
    description: "The West Indies islands offer the ultimate Caribbean experience — Barbados' colonial plantation houses and rum distilleries, Trinidad's Carnival, the volcanic St. Lucia, Tobago's coral reefs, and the sailing heaven of the Grenadines. 365 Tours designs private island-hopping Caribbean journeys.",
    highlights: ["Barbados rum distillery tour", "Trinidad Carnival", "St. Lucia Pitons hike", "Tobago reef snorkelling", "Grenadines sailing"],
    experiences: ["Beach", "Culture", "Adventure", "Nature", "Food"],
    duration: "10–16 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Zambia",
    slug: "zambia",
    continent: "Africa",
    tagline: "Victoria Falls & walking safaris in South Luangwa",
    description: "Zambia is Africa's finest wilderness safari destination for those who want something beyond the crowds — the incomparable South Luangwa walking safaris, the thundering Victoria Falls from the Zambian side, Lower Zambezi canoe safaris, and the emerald season rains. A genuinely wild private tour.",
    highlights: ["Victoria Falls (Zambia side)", "South Luangwa walking safari", "Lower Zambezi canoe safari", "Kafue National Park", "Royal Livingstone experience"],
    experiences: ["Wildlife", "Adventure", "Nature", "Luxury"],
    duration: "10–14 days",
    bestTime: "June – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Zimbabwe",
    slug: "zimbabwe",
    continent: "Africa",
    tagline: "Victoria Falls, Hwange lions & Great Zimbabwe ruins",
    description: "Zimbabwe is one of Africa's most extraordinary and underrated destinations — Victoria Falls in full spray, Hwange National Park's vast elephant herds, the ancient stone city of Great Zimbabwe, and the granite wilderness of Matobo Hills. 365 Tours pairs Zimbabwe with Botswana or Zambia for a definitive southern Africa private tour.",
    highlights: ["Victoria Falls spray walk", "Hwange elephant herds", "Great Zimbabwe ruins", "Matobo Hills rhino trek", "Canoe safari, Zambezi"],
    experiences: ["Wildlife", "History", "Nature", "Adventure"],
    duration: "10–16 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
];

// ── Merge real scraped catalog images over the editorial data ──
// Every editorial destination gets its actual 365tours.in photos, flag and regions.
// The card/hero images are switched from stock photos to the real gallery shots.
for (const dest of destinations) {
  const entry = catalog[dest.slug];
  if (!entry) continue;
  dest.id = entry.id;
  dest.gallery = entry.gallery;
  dest.flag = entry.flag || undefined;
  dest.regions = entry.regions;
  if (entry.gallery.length > 0) {
    dest.image = entry.gallery[0];
    dest.heroImage = entry.gallery[0];
  }
}

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export function getAllSlugs(): string[] {
  return destinations.map((d) => d.slug);
}

export const experienceColors: Record<Experience, string> = {
  Culture:    "bg-violet-100 text-violet-700",
  Nature:     "bg-emerald-100 text-emerald-700",
  Adventure:  "bg-orange-100 text-orange-700",
  Wildlife:   "bg-amber-100 text-amber-700",
  Food:       "bg-rose-100 text-rose-700",
  Romance:    "bg-pink-100 text-pink-700",
  History:    "bg-yellow-100 text-yellow-700",
  Beach:      "bg-sky-100 text-sky-700",
  Luxury:     "bg-stone-100 text-stone-700",
};
