import catalogImages from "./catalog-images.json";

export type Experience = "Culture" | "Nature" | "Adventure" | "Wildlife" | "Food" | "Romance" | "History" | "Beach" | "Luxury";

export interface Destination {
  name: string;
  slug: string;
  continent: string;
  tagline: string;
  description: string;
  highlights: string[];
  experiences: Experience[];
  duration: string;
  bestTime: string;
  image: string;
  heroImage: string;
  /** Catalog id from 365tours.in (e.g. "365T_00002") */
  id?: string;
  /** Real destination photos scraped from 365tours.in (local /destinations/… paths) */
  gallery?: string[];
  /** Country flag image (local path) */
  flag?: string;
  /** Regions / cities offered within this destination */
  regions?: string[];
  /** Signature itinerary photos with their duration + places covered */
  itineraries?: Itinerary[];
  /** "Recipe book" feature image for the Travel Rewards card */
  recipeImage?: string;
}

export interface Itinerary {
  src: string;
  days: string;
  places: string[];
}

type CatalogEntry = {
  id: string;
  gallery: string[];
  recipeImage: string;
  flag: string;
  regions: string[];
  itineraries?: Itinerary[];
  /** The destination's real hero banner (tour_images/<id>/main_image.jpg) */
  mainImage?: string;
};

const catalog = catalogImages as Record<string, CatalogEntry>;

export const destinations: Destination[] = [
  {
    name: "Antarctica",
    slug: "antarctica",
    continent: "Antarctica",
    tagline: "The last great wilderness on Earth",
    description: "Antarctica the most isolated place on Earth. Explore and experience its unique wildlife, spectacular natural landscape and unique icebergs. These are some of the reasons to visit this one of a kind continent on Earth.",
    highlights: ["Penguin colonies at close range", "Glacial zodiac cruises", "Antarctic Peninsula landscapes", "Aurora Australis viewing", "Research station visits"],
    experiences: ["Adventure", "Nature", "Luxury"],
    duration: "14–21 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1551085254-e96b210db58a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1551085254-e96b210db58a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Argentina",
    slug: "argentina",
    continent: "South America",
    tagline: "Tango, Patagonia & Gaucho culture",
    description: "Argentina has a distinct & beautiful geography, interesting history, thriving nightlife, unique local cuisine, thundering Iguazu Falls and host of adventure sports. These are some of the reasons to visit ‘THE LAND OF SILVER’.",
    highlights: ["Iguazu Falls at sunrise", "Perito Moreno Glacier", "Buenos Aires tango culture", "Mendoza wine estates", "Patagonia trekking"],
    experiences: ["Nature", "Adventure", "Food", "Culture"],
    duration: "12–18 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Armenia",
    slug: "armenia",
    continent: "Asia",
    tagline: "Ancient monasteries & Caucasus highlands",
    description: "Armenia is the first Christian country in the world. It has a rich cultural heritage ancient sights, delicious food, spectacular natural beauty and the longest ropeway in the world-5.80 Kms. These are some of the reasons to visit ‘ THE COUNTRY OF STONES’",
    highlights: ["Geghard Monastery", "Lake Sevan", "Yerevan's Republic Square", "Mount Ararat views", "Noravank Canyon"],
    experiences: ["History", "Culture", "Nature"],
    duration: "8–12 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1565008576549-57569a49371d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Australia",
    slug: "australia",
    continent: "Oceania",
    tagline: "Red deserts, coral reefs & iconic cities",
    description: "Australia has captivated the world with its unique natural wonders and wildlife. Enjoy the solitude of many small towns, understand the Aboriginal culture, pristine beaches, stunning nature & wildlife and get soaked in the largest Barrier Reef in the world. These are some of the reasons to visit ‘THE LAND DOWN UNDER’.",
    highlights: ["Great Barrier Reef snorkelling", "Uluru at sunrise", "Sydney Opera House", "Daintree Rainforest", "Great Ocean Road"],
    experiences: ["Nature", "Adventure", "Beach", "Culture"],
    duration: "14–21 days",
    bestTime: "September – November",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Austria",
    slug: "austria",
    continent: "Europe",
    tagline: "Mozart, Alps & Viennese grandeur",
    description: "Austria has plenty of natural, architectural and cultural beauties. It is one of Europe’s hidden gems. Admire the beautiful cities, breath taking Alps and stunning architecture. These are some of the reason to visit the ‘IMPERIAL & ROYAL COUNTRY’.",
    highlights: ["Vienna's Schönbrunn Palace", "Hallstatt village", "Salzburg Old Town", "Sound of Music trail", "Alpine skiing in Innsbruck"],
    experiences: ["Culture", "History", "Nature", "Luxury"],
    duration: "8–12 days",
    bestTime: "May – September & December",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Azerbaijan",
    slug: "azerbaijan",
    continent: "Asia",
    tagline: "Fire temples, mud volcanoes & the Caspian",
    description: "Azerbaijan is a real blend of East and West, with a deep and intriguing history. Experience and explore the mud volcanoes one of a kind natural wonder, wonderful mountain villages, fire temple and hiking in the Caucasus. These are some of the reasons to visit ‘THE LAND OF FIRE’.",
    highlights: ["Baku Old City (Icheri Sheher)", "Gobustan Mud Volcanoes", "Ateshgah Fire Temple", "Sheki Khan's Palace", "Caspian Sea coast"],
    experiences: ["Culture", "History", "Adventure"],
    duration: "7–10 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Belize",
    slug: "belize",
    continent: "Central America",
    tagline: "Mayan ruins, blue holes & jungle lodges",
    description: "Belize is the most popular eco tourism destination in Central America. It has its lush rainforest, pristine beaches ancient Maya Cities, potpourri of islands and home to the world renowned Blue Hole. These are some of the reasons to visit the ‘BRITISH HONDURAS’.",
    highlights: ["Great Blue Hole diving", "Actun Tunichil Muknal cave", "Tikal day trip", "Caye Caulker relaxation", "Howler Monkey watching"],
    experiences: ["Adventure", "Nature", "History", "Beach"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bhutan",
    slug: "bhutan",
    continent: "Asia",
    tagline: "Gross National Happiness & Tiger's Nest",
    description: "Bhutan is the perfect abode for peace and fresh air. With it’s unique culture, awe inspiring Tiger’s Nest, pumping adventures, fascinating nature and landscape, are some of the reasons to visit this land of the thunder dragon.",
    highlights: ["Tiger's Nest Monastery (Paro Taktsang)", "Punakha Dzong", "Dochula Pass rhododendron forests", "Thimphu weekend market", "Black-necked crane festival"],
    experiences: ["Culture", "Nature", "History", "Adventure"],
    duration: "8–12 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1553958700-2e1e6db4114d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1553958700-2e1e6db4114d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bolivia",
    slug: "bolivia",
    continent: "South America",
    tagline: "Salt flats, altiplano & Amazon headwaters",
    description: "Bolivia is celebrated for its colorful history, fascinating customs, diverse wildlife and jaw dropping landscapes. Experience the out of the world wildlife encounters, colorful history, fascinating cultures and fun filled fiestas. These are some of the reasons to visit the ‘TIBET OF THE AMERICAS’.",
    highlights: ["Salar de Uyuni salt flats", "Lake Titicaca", "Death Road cycling", "La Paz witches' market", "Madidi National Park"],
    experiences: ["Adventure", "Nature", "Culture"],
    duration: "10–14 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1580492516014-4a28729eb08e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580492516014-4a28729eb08e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Botswana",
    slug: "botswana",
    continent: "Africa",
    tagline: "Okavango Delta & exclusive bush camps",
    description: "Botswana is dubbed as the ultimate Safari Experience. Explore & experience the game drives, wide choice eco friendly lodges, grassy plains of Okavango Delta and witness the once in life time the annual Zebra migration. These are some of the reasons to visit the ‘LAND OF THE TSWANA’.",
    highlights: ["Okavango Delta mokoro canoe", "Chobe National Park elephants", "Moremi Game Reserve", "Makgadikgadi Pans", "Wild dog sightings"],
    experiences: ["Wildlife", "Nature", "Luxury", "Adventure"],
    duration: "10–16 days",
    bestTime: "June – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Brazil",
    slug: "brazil",
    continent: "South America",
    tagline: "Amazon, Carnival & tropical coastlines",
    description: "Brazil is a must visit destination for any traveler. Experience and explore its pristine beaches, breath taking landscapes & Eco systems, tasty cuisine, alluring Amazon and an unique culture. These are some of the reasons to visit this ‘SOCCER NATION’.",
    highlights: ["Amazon River expedition", "Rio de Janeiro & Christ the Redeemer", "Iguazu Falls (Brazilian side)", "Pantanal jaguar safari", "Salvador's Afro-Brazilian culture"],
    experiences: ["Nature", "Wildlife", "Culture", "Beach", "Adventure"],
    duration: "14–21 days",
    bestTime: "April – September",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Bulgaria",
    slug: "bulgaria",
    continent: "Europe",
    tagline: "Rose valleys, monasteries & Black Sea beaches",
    description: "Bulgaria is an amazing destination that is totally underrated. It has its charming towns and villages, sunny beaches and golden sands in the black sea coast, charming monasteries, breathtaking mountains, rich history and extremely friendly people. These are some of the reasons to visit the ‘LAND OF ROSES’.",
    highlights: ["Rila Monastery", "Plovdiv Old Town", "Rose Valley festival", "Belogradchik Rocks", "Nessebar Old Town"],
    experiences: ["History", "Culture", "Nature", "Beach"],
    duration: "8–12 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1601392842425-6b8a6f7d3a2a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1601392842425-6b8a6f7d3a2a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cambodia",
    slug: "cambodia",
    continent: "Asia",
    tagline: "Angkor Wat & Mekong river life",
    description: "Cambodia has something for everyone. Stunning and fascinating temples at Angkor, spicy foods with unique flavors, rich history, pristine beaches, diverse landscape and bargain shopping. These are some of the reasons to visit the “ LAND OF THE KHMER'.",
    highlights: ["Angkor Wat sunrise", "Bayon temple faces", "Tonle Sap floating village", "Royal Palace Phnom Penh", "Koh Rong beaches"],
    experiences: ["History", "Culture", "Nature", "Beach"],
    duration: "8–12 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1540428296098-3e6d5e3b3d3e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1540428296098-3e6d5e3b3d3e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Chile",
    slug: "chile",
    continent: "South America",
    tagline: "Patagonia, Atacama & Easter Island",
    description: "Chile is unlike any other country. It is well known for its natural beauty, diverse landscapes, vineyards, volcanoes, deserts, beaches, lakes, glaciers and forests. These are some fo the reasons to visit ‘THE COUNTRY OF POETS”.",
    highlights: ["Torres del Paine trekking", "Atacama stargazing", "Easter Island moai", "Valle de la Luna", "Chiloé Island culture"],
    experiences: ["Adventure", "Nature", "Culture", "History"],
    duration: "14–21 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "China",
    slug: "china",
    continent: "Asia",
    tagline: "The Great Wall, silk roads & ancient dynasties",
    description: "China has the richest breadth of culture, impressive ancient heritage, varied & spectacular natural wonders, variety of cuisine, rare wildlife and easily accessible with its efficient transport systems. These are some of the reasons to visit the ‘LAND OF THE RED DRAGON’.",
    highlights: ["Great Wall at Mutianyu", "Terracotta Army, Xi'an", "Li River cruise, Guilin", "Shanghai Bund", "Zhangjiajie glass bridge"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "14–21 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Colombia",
    slug: "colombia",
    continent: "South America",
    tagline: "Cartagena, coffee country & the Amazon",
    description: "Colombia is rich with its Caribbean coast line, rainforest, endangered animals, unique eco systems and the wonderful Andes mountain range. These are some of the reasons to visit the “GATEWAY TO SOUTH AMERICA’",
    highlights: ["Cartagena's walled old city", "Salento coffee farm tour", "Medellín transformation story", "Tayrona National Park", "Amazon birding"],
    experiences: ["Culture", "Food", "Nature", "History", "Adventure"],
    duration: "10–14 days",
    bestTime: "December – March & June – August",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Costa Rica",
    slug: "costa-rica",
    continent: "Central America",
    tagline: "Pura Vida — volcanoes, sloths & rainforests",
    description: "Costa Rica is a beautiful country filled with rainforests, beaches, river valleys and bio diverse wildlife. Explore and experience its 27 National Parks, 60 dormant volcanoes and host of activities and tours. These are some of the reasons to visit the “HUMMING BIRD CAPITAL OF THE WORLD”.",
    highlights: ["Monteverde Cloud Forest", "Arenal Volcano zipline", "Manuel Antonio wildlife", "Tortuguero sea turtles", "Corcovado jungle immersion"],
    experiences: ["Nature", "Wildlife", "Adventure", "Beach"],
    duration: "10–14 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Croatia",
    slug: "croatia",
    continent: "Europe",
    tagline: "Dubrovnik's walls, islands & Adriatic blue",
    description: "Croatia is famous for its pristine beaches & dramatic cliffs of the Dalmatian coast. Experience and explore the Plitvice National Park- most breathtaking natural wonder, charming cities and vibrant nightlife. These are some of the reasons to visit ‘REPUBLIKA HRVATSKA’.",
    highlights: ["Dubrovnik Old Town walls", "Plitvice Lakes waterfalls", "Hvar island nightlife", "Diocletian's Palace, Split", "Sailing the Dalmatian coast"],
    experiences: ["Culture", "Beach", "History", "Nature", "Romance"],
    duration: "10–14 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1555990793-da11153b2473?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555990793-da11153b2473?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cuba",
    slug: "cuba",
    continent: "Caribbean",
    tagline: "Vintage Havana, salsa & Caribbean beaches",
    description: "Cuba is the largest island in the Caribbean and is certainly not short on attractions. Its pristine beaches, colorful architecture, friendly people and full of natural beauty. These are some of the reasons to visit the ‘PEARL OF THE ANTILLES’.",
    highlights: ["Havana Old Town", "Trinidad colonial streets", "Vinales Valley tobacco farms", "Varadero beaches", "Classic car tour"],
    experiences: ["Culture", "History", "Beach", "Food"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1500759285222-a95626b934cb?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Cyprus",
    slug: "cyprus",
    continent: "Europe",
    tagline: "Aphrodite's island — beaches & Byzantine heritage",
    description: "Cyprus has sparkling sea, great traditional dishes, cultural diversity, unmatched partying, rich history, interesting monuments and friendly people. These are some of the reasons to visit the ‘ISLAND OF LOVE’.",
    highlights: ["Paphos Archaeological Park", "Troodos Mountain monasteries", "Famagusta walled city", "Aphrodite's Rock", "Akamas Peninsula"],
    experiences: ["History", "Culture", "Beach", "Nature"],
    duration: "7–10 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1558642084-fd07fae5282e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558642084-fd07fae5282e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Czech Republic",
    slug: "czech-republic",
    continent: "Europe",
    tagline: "Prague's fairy-tale spires & Bohemian castles",
    description: "Czech Republic has a rich & colorful history. It has its countless castles, well preserved UNESCO sites, spectacular national parks, charming cities and vibrant nightlife. These are some of the reasons to visit ‘CZECHIA”.",
    highlights: ["Prague Old Town Square", "Charles Bridge at dawn", "Ceský Krumlov castle", "Kutná Hora Bone Church", "Bohemian wineries"],
    experiences: ["History", "Culture", "Food", "Romance"],
    duration: "8–12 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Dubai",
    slug: "dubai",
    continent: "Middle East",
    tagline: "Ultramodern skylines meet ancient desert culture",
    description: "Dubai & Abu Dhabi are one of the unique cities in the world. Experience the cultural diversity, see the desert & sky scrapers, witness unique architecture & splurge on shopping. These are some of the reasons to visit the ‘CITY OF GOLD’.",
    highlights: ["Burj Khalifa observation deck", "Desert safari & BBQ", "Gold & Spice Souk", "Dubai Frame", "Abra ride in Dubai Creek"],
    experiences: ["Luxury", "Culture", "Adventure", "Food"],
    duration: "5–8 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ecuador",
    slug: "ecuador",
    continent: "South America",
    tagline: "Galápagos, cloud forests & the equator",
    description: "Ecuador brings many surprises-most extraordinary wildlife filled islands on the planet. Experience & explore Galapagos islands, second highest capital in the world, active volcanoes, rain forests & glaciers. These are some of the reasons to visit ‘LIGHT OF AMERICA’",
    highlights: ["Galápagos giant tortoises", "Amazon jungle overnight", "Avenue of Volcanoes", "Quito Old Town (UNESCO)", "Otavalo indigenous market"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "12–16 days",
    bestTime: "June – September",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Egypt",
    slug: "egypt",
    continent: "Africa",
    tagline: "Pyramids, pharaohs & Nile river journeys",
    description: "Egypt boasts of a spectacular landscape filled with cultural gems. sun, sea & sand interspersed with a touch of exotic culture & heritage, the gushing river Nile, jaw dropping Pyramids, ancient monuments, vast deserts & world famous coral reefs. These are some of the reasons to visit 'GIFT OF THE NILE'.",
    highlights: ["Great Pyramids & Sphinx", "Valley of the Kings", "Luxor Temple by night", "Nile felucca sunset cruise", "Abu Simbel temples"],
    experiences: ["History", "Culture", "Luxury", "Adventure"],
    duration: "10–14 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1539768942893-daf53e448371?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1539768942893-daf53e448371?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Estonia",
    slug: "estonia",
    continent: "Europe",
    tagline: "Medieval Tallinn & Baltic island escapes",
    description: "Estonia is truly the gem of Europe. It has its colorful streets, unique wooden houses & signs, building with Medieval touch beautiful sandy beaches with vibrant night life. These are some of the reasons to visit ‘MARY’S LAND’.",
    highlights: ["Tallinn Old Town ramparts", "Lahemaa National Park", "Saaremaa island", "Open Air Museum", "Pärnu beach resort"],
    experiences: ["History", "Culture", "Nature"],
    duration: "6–9 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1564594985645-4427056e22e2?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1564594985645-4427056e22e2?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ethiopia",
    slug: "ethiopia",
    continent: "Africa",
    tagline: "Rock-hewn churches, ancient empires & the Rift Valley",
    description: "Ethiopia is a land of ancient culture and some spectacular landscapes. Experience and explore the rock hewn churched, hiking the mountains, diverse cuisine, rich culture and vibrant night life. These are some of the reasons to visit ‘THE LAND OF 13 MONTHS OF SUNSHINE’.",
    highlights: ["Lalibela rock-hewn churches", "Simien Mountains trekking", "Omo Valley tribes", "Aksum obelisks", "Danakil Depression"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "12–18 days",
    bestTime: "October – May",
    image: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1611348586804-61bf6c080437?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Finland",
    slug: "finland",
    continent: "Europe",
    tagline: "Northern lights, saunas & reindeer sleighs",
    description: "Finland has more forests and water than any where else in the world. It is one of the best spots to view Northern Lights, charming cities, vibrant nightlife, host of activities & sports and some of the craziest events. These are some of the reasons to visit the ‘LAND OF A THOUSAND LAKES’.",
    highlights: ["Aurora Borealis in Lapland", "Santa Claus Village, Rovaniemi", "Helsinki Design District", "Finnish lakeland sauna", "Husky safari"],
    experiences: ["Nature", "Adventure", "Culture", "Luxury"],
    duration: "8–12 days",
    bestTime: "December – March (Aurora) | June – August (Midnight Sun)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "France",
    slug: "france",
    continent: "Europe",
    tagline: "Paris, Provence & the French Riviera",
    description: "France is the world’s most visited country. It has its glamorous cities, picturesque villages, spectacular beaches and mind blowing museums. These are some of the reasons to visit ‘THE COUNTRY OF HUMAN RIGHTS’",
    highlights: ["Eiffel Tower & Louvre, Paris", "Provence lavender fields", "Loire Valley châteaux", "French Riviera coastline", "Burgundy wine tasting"],
    experiences: ["Culture", "Food", "Romance", "History", "Luxury"],
    duration: "10–16 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Georgia",
    slug: "georgia",
    continent: "Asia",
    tagline: "Caucasus towers, ancient wine & mountain villages",
    description: "Georgia is a country shrouded in mystery. Explore and experience its natural beauty, charming villages, architectural buildings, mysterious cave cities, unique museums and Georgian hospitality. These are some of the reasons to visit the ‘BIRTHPLACE OF WINE’.",
    highlights: ["Gergeti Trinity Church, Kazbegi", "Svaneti towers", "Tbilisi Old Town", "Uplistsikhe cave city", "Georgian wine tasting in Kakheti"],
    experiences: ["Culture", "History", "Nature", "Food", "Adventure"],
    duration: "8–12 days",
    bestTime: "May – June & September – October",
    image: "https://images.unsplash.com/photo-1562978559-3e3a8d9b4a3a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1562978559-3e3a8d9b4a3a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Germany",
    slug: "germany",
    continent: "Europe",
    tagline: "Castles, Christmas markets & Bavarian culture",
    description: "Germany’s multitude of regional identities offers a cornucopia of distinct experiences to meet all kinds of expectations. Explore and experience its rich historical attractions, unique festivals, cultural diversity and stunning landscapes. These are some of the reasons to visit ‘DEUTSCHLAND’.",
    highlights: ["Neuschwanstein Castle", "Berlin Wall & Brandenburg Gate", "Black Forest drive", "Cologne Cathedral", "Bavarian Alps"],
    experiences: ["History", "Culture", "Nature", "Food"],
    duration: "10–14 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Greece",
    slug: "greece",
    continent: "Europe",
    tagline: "Santorini sunsets, ancient ruins & island life",
    description: "Greece is the cradle of Western civilization and a wonderful destination all year around. Experience overwhelming hospitality, wide choice in food & drink, fascinating beaches, remarkable history, sensational Greek islands and a superb night life. These are some of the reasons to visit the ‘HELLENIC REPUBLIC’.",
    highlights: ["Santorini caldera sunset", "Acropolis & Parthenon, Athens", "Delphi Oracle ruins", "Mykonos island town", "Meteora monasteries"],
    experiences: ["History", "Culture", "Beach", "Food", "Romance"],
    duration: "10–14 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Guatemala",
    slug: "guatemala",
    continent: "Central America",
    tagline: "Mayan pyramids, Lake Atitlán & volcanoes",
    description: "Guatemala has Tikal which is the largest and the well known Mayan Ruins. Besides you can explore and experience its heritage sites, Lake Atitlan, water falls, beaches and jungles. These are some of the reasons to visit the ‘LAND OF ETERNAL SPRING’.",
    highlights: ["Tikal ruins at sunrise", "Lake Atitlán by boat", "Antigua colonial streets", "Acatenango Volcano hike", "Chichicastenango market"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1591703823184-53f23cbc8f90?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1591703823184-53f23cbc8f90?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Hungary",
    slug: "hungary",
    continent: "Europe",
    tagline: "Budapest's baths, Danube & Great Plains",
    description: "Hungary is well known for its natural beauty, Gothic style architecture, natural spring sources, beautiful Danube river and UNESCO sites. These are some of the reasons to visit the ‘LAND OF MAGYARS’",
    highlights: ["Budapest Parliament building", "Széchenyi thermal baths", "Fisherman's Bastion sunset", "Ruin bars of Pest", "Eger wine caves"],
    experiences: ["Culture", "History", "Food", "Romance"],
    duration: "7–10 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1549916919-ac57e70f8b67?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1549916919-ac57e70f8b67?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Iceland",
    slug: "iceland",
    continent: "Europe",
    tagline: "Northern lights, geysers & midnight sun",
    description: "Iceland is the best spot to view Northern Lights. It has its Blue Lagoons, Mountains, Volcanoes, Lakes, ice caves, glaciers, adventure activities and of course the midnight sun. These are some of the reasons to visit ‘THE LAND OF ICE AND FIRE”.",
    highlights: ["Golden Circle (Geysir, Gullfoss)", "Northern Lights hunting", "Blue Lagoon geothermal spa", "Jökulsárlón glacier lagoon", "Snæfellsnes Peninsula"],
    experiences: ["Nature", "Adventure", "Luxury", "Romance"],
    duration: "8–12 days",
    bestTime: "June – August (Midnight Sun) | September – March (Aurora)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Indonesia",
    slug: "indonesia",
    continent: "Asia",
    tagline: "Bali temples, Komodo dragons & Raja Ampat reefs",
    description: "The Indonesian archipelago is made up of whopping 17,800 islands. Explore the countless pristine islands, rediscover Bali, stunning wildlife, close encounters with Komodo dragon, sunrise at Borobudur and trek the active volcanoes and mountains. These are some of the reasons to visit ‘THE EMERALD OF THE EQUATOR'.",
    highlights: ["Borobudur sunrise", "Komodo dragon tracking", "Bali rice terrace walk", "Raja Ampat diving", "Yogyakarta batik tradition"],
    experiences: ["Culture", "Nature", "Adventure", "Beach", "Wildlife"],
    duration: "14–21 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Iran",
    slug: "iran",
    continent: "Asia",
    tagline: "Persian empire, blue mosques & ancient bazaars",
    description: "Iran is like nowhere else. You can experience all four seasons in a single trip. Travel back in time, try delightful Persian cuisine, stroll in the beautiful Persian gardens and the Iranian hospitality will amaze you. These are some of the reasons to visit ‘THE LAND OF ARYANS’.",
    highlights: ["Nasir al-Mulk Mosque, Shiraz", "Persepolis ruins", "Naqsh-e Jahan Square, Isfahan", "Golestan Palace, Tehran", "Kashan historic houses"],
    experiences: ["History", "Culture"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Israel",
    slug: "israel",
    continent: "Middle East",
    tagline: "Jerusalem's old city, Dead Sea & Tel Aviv beaches",
    description: "Israel is a country with amazing nature, countless historic & religious sites. Experience the rich history, pristine beaches, countless places to eat and amazing local culture. These are some of the reasons to visit the ‘HOLY LAND’.",
    highlights: ["Jerusalem Old City & Western Wall", "Dead Sea float", "Masada sunrise cable car", "Tel Aviv Carmel Market", "Petra (Jordan) day trip"],
    experiences: ["History", "Culture", "Beach", "Adventure"],
    duration: "8–12 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Italy",
    slug: "italy",
    continent: "Europe",
    tagline: "Rome, Renaissance & la dolce vita",
    description: "Italy is the dream destination for any traveler. It has its Roman ruins, Renaissance works, stunning villages, legendary cities and treasure trove of UNESO sites. These are some of the reasons to visit ‘LATIN ITALIA’.",
    highlights: ["Colosseum & Vatican, Rome", "Gondola in Venice", "Uffizi Gallery, Florence", "Amalfi Coast drive", "Trulli houses, Alberobello"],
    experiences: ["History", "Culture", "Food", "Romance", "Luxury"],
    duration: "12–18 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555992336-03a23c7b20ee?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Japan",
    slug: "japan",
    continent: "Asia",
    tagline: "Cherry blossoms, temples & neon modernity",
    description: "Japan’s culture is an interesting blend of Eastern traditions and Western modernity. It is one of the oldest civilization and has a stunning and diverse history. Explore and experience the beautiful landscape & mountains, cuisine, bullet trains and temples. These are some of the reasons to visit the ‘LAND OF THE RISING SUN’.",
    highlights: ["Fushimi Inari torii gates", "Tokyo shibuya crossing", "Hiroshima Peace Memorial", "Arashiyama bamboo grove", "Mt. Fuji view from Hakone"],
    experiences: ["Culture", "History", "Food", "Nature", "Luxury"],
    duration: "12–18 days",
    bestTime: "March – May (Cherry Blossom) | November – December (Autumn)",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Jordan",
    slug: "jordan",
    continent: "Middle East",
    tagline: "Petra's rose-red city & Wadi Rum desert",
    description: "Jordan with its Petra, one of the wonders, Dana Biosphere largest nature reserve, hospitable people, Middle Eastern Art & Culture & ancient civilizations are some of the reasons to visit this historical country.",
    highlights: ["Petra Treasury at sunrise", "Wadi Rum jeep & camp", "Dead Sea float", "Jerash Roman ruins", "Aqaba snorkelling"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "7–10 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548786811-dd6e453ccca7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Kenya",
    slug: "kenya",
    continent: "Africa",
    tagline: "Masai Mara, Great Migration & Swahili coast",
    description: "Kenya is the epicentre of the greatest spectacle on Earth- The Wildebeest migration. Take a game drive in some of the best parks in the world, see the Big 5, visit pristine beaches, sail in the Kenyan coast & learn a bit of history in some UNESCO world heritage sites.",
    highlights: ["Great Migration, Masai Mara", "Amboseli elephant herds", "Lamu Old Town", "Mount Kenya trekking", "Giraffe Centre, Nairobi"],
    experiences: ["Wildlife", "Nature", "Culture", "Adventure", "Luxury"],
    duration: "10–16 days",
    bestTime: "July – October (Migration) | January – February",
    image: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1534177616072-ef7dc120449d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Laos",
    slug: "laos",
    continent: "Asia",
    tagline: "Luang Prabang monks, Mekong & 4000 Islands",
    description: "Laos boasts of countless caves, captivating markets, colorful temples with intriguing history and Buddhist culture & practices. These are some of the reasons to visit ‘THE LAND OF THE MILLION ELEPHANTS’.",
    highlights: ["Alms-giving ceremony, Luang Prabang", "Kuang Si Falls", "Plain of Jars", "Mekong slow boat", "Si Phan Don (4000 Islands)"],
    experiences: ["Culture", "Nature", "History", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – February",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Latvia",
    slug: "latvia",
    continent: "Europe",
    tagline: "Art Nouveau Riga & Baltic forests",
    description: "Lativa has its lush one forests, theatrical style architecture & design, beautiful beaches, remarkable palaces and ancient castles. These are some of the reasons to visit the ‘LAND OF BLUE LAKES’.",
    highlights: ["Riga Old Town", "Art Nouveau district walk", "Gauja National Park", "Jurmala beach resort", "Turaida Castle"],
    experiences: ["Culture", "History", "Nature"],
    duration: "6–8 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Lithuania",
    slug: "lithuania",
    continent: "Europe",
    tagline: "Baroque Vilnius, the Hill of Crosses & Baltic coast",
    description: "Lithuania the southern most of the three Baltic countries has its vibrant capital, charming castles, peaceful Baltic Sea, unique festivals and remarkable natural environment. These are some of the reasons to visit the ‘LAND OF STORKS’.",
    highlights: ["Vilnius Old Town", "Hill of Crosses", "Curonian Spit sand dunes", "Trakai Island Castle", "Palanga amber museum"],
    experiences: ["History", "Culture", "Nature"],
    duration: "6–8 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580674684081-7617fbf3d745?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Macau",
    slug: "macau",
    continent: "Asia",
    tagline: "Portuguese heritage meets Chinese gaming capital",
    description: "Macau features the biggest casinos & posh hotels. Besides it has great beaches, colonial past and host of activities and sights. These are some of the reasons to visit ‘THE LAS VEGAS OF ASIA’",
    highlights: ["Ruins of St. Paul's", "Senado Square", "Taipa Village", "Macau Tower bungee", "A-Ma Temple"],
    experiences: ["History", "Culture", "Food"],
    duration: "3–5 days",
    bestTime: "October – December",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Madagascar",
    slug: "madagascar",
    continent: "Africa",
    tagline: "Lemurs, baobab avenues & otherworldly nature",
    description: "Madagascar is one of the most charismatic and interesting country. Experience and explore its rare flora & fauna, dense rain forests, pristine beaches and delicious cuisine. These are some of the reasons to visit ‘THE RED ISLAND’.",
    highlights: ["Avenue of Baobabs, Morondava", "Lemur sightings, Ranomafana", "Tsingy de Bemaraha", "Whale watching, Ile Sainte-Marie", "Nosy Be beaches"],
    experiences: ["Wildlife", "Nature", "Adventure", "Beach"],
    duration: "14–18 days",
    bestTime: "April – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Malawi",
    slug: "malawi",
    continent: "Africa",
    tagline: "The warm heart of Africa & Lake Malawi",
    description: "Malawi is a small country which is totally unspoilt and is well known for the extraordinary fresh water Lake Malawi. Experience and explore the wild life, diving and snorkeling on its clear waters, mountain biking, birding and hiking. These are some of the reasons to visit ‘THE WARM HEART OF AFRICA’",
    highlights: ["Lake Malawi kayaking", "Liwonde National Park boat safari", "Nyika Plateau hiking", "Livingstonia Mission", "Cape Maclear snorkelling"],
    experiences: ["Wildlife", "Nature", "Adventure", "Beach"],
    duration: "10–14 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Malaysia",
    slug: "malaysia",
    continent: "Asia",
    tagline: "Rainforests, orangutans & Petronas Towers",
    description: "Malaysia with its cultural diversity, long standing tradition, pristine beaches, old tropical jungles & rainforests, natural monuments & one of a kind wildlife. These are some of the reasons to visit the ‘Land of the Indigenous Malay’.",
    highlights: ["Orangutan spotting, Borneo", "Petronas Twin Towers, KL", "Penang street food", "Perhentian Islands diving", "Cameron Highlands tea estates"],
    experiences: ["Wildlife", "Culture", "Nature", "Food", "Beach"],
    duration: "12–16 days",
    bestTime: "December – February",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Maldives",
    slug: "maldives",
    continent: "Asia",
    tagline: "Overwater villas & Indian Ocean reefs",
    description: "Maldives is well known for its crystalline waters and white sandy beaches. It has myriad marine life, great resorts and certainly once in a lifetime visit.",
    highlights: ["Overwater villa sunrise", "Manta ray snorkelling", "Whale shark dive", "Private sandbank picnic", "Sunset dolphin cruise"],
    experiences: ["Beach", "Luxury", "Romance", "Nature"],
    duration: "6–10 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mauritius",
    slug: "mauritius",
    continent: "Africa",
    tagline: "Turquoise lagoons, creole culture & luxury resorts",
    description: "Mauritius is the stamping ground for holidays. It has its white sandy beaches, turquoise lagoon, lush vegetation, host of activities and rich cultural values. These are some of the reasons to visit ‘PEARL OF THE INDIAN OCEAN’.",
    highlights: ["Blue Bay Marine Park snorkelling", "Black River Gorges hike", "Chamarel Coloured Earths", "Port Louis market", "Ile aux Cerfs lagoon"],
    experiences: ["Beach", "Luxury", "Romance", "Nature", "Culture"],
    duration: "8–12 days",
    bestTime: "May – December",
    image: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mexico",
    slug: "mexico",
    continent: "North America",
    tagline: "Mayan pyramids, Day of the Dead & Pacific beaches",
    description: "Mexico is one of the must visit countries. Experience the secret island escapes, colonial towns, Caribbean coastline, amazing cuisine, world heritage sites and there is something for everyone. These are some of the reasons to visit the ‘LAND OF ENCHANTMENT’.",
    highlights: ["Chichén Itzá Pyramid", "Mexico City's Frida Kahlo Museum", "Cenote swimming, Yucatán", "Oaxaca food trail", "Monarch butterfly migration"],
    experiences: ["History", "Culture", "Food", "Nature", "Beach"],
    duration: "12–18 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1535818860179-a85038b51b15?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1535818860179-a85038b51b15?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mongolia",
    slug: "mongolia",
    continent: "Asia",
    tagline: "Gobi Desert, nomad stays & the Naadam Festival",
    description: "Mongolia is a country of incredible natural beauty that still preserves the traditional nomadic way of life. Visit the Gobi Desert that was Dinosaurs native land, watch the Naadam festival the unique sporting event, experience its pristine nature & landscapes and abundant wildlife you can immerse yourself in. These are some of the reasons to visit the ‘LAND OF THE MONGOLS’.",
    highlights: ["Naadam Festival (July)", "Gobi Desert camel trek", "Ger camp homestay", "Terelj National Park", "Karakorum monastery"],
    experiences: ["Culture", "Adventure", "Nature", "Wildlife"],
    duration: "10–16 days",
    bestTime: "June – September",
    image: "https://images.unsplash.com/photo-1536329583941-14287ec6fc4e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1536329583941-14287ec6fc4e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Morocco",
    slug: "morocco",
    continent: "Africa",
    tagline: "Sahara dunes, medinas & Atlas Mountains",
    description: "Morocco has its Sahara Desert, scenic Atlas mountains, colorful markets, vibrant imperial cities, golden sand beaches & delicious food are some of the reasons to visit 'THE LAND OF COLOURS'.",
    highlights: ["Sahara camel trek, Merzouga", "Fez medina walk", "Chefchaouen blue streets", "Marrakech souks", "High Atlas Berber village"],
    experiences: ["Culture", "History", "Adventure", "Food", "Nature"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Mozambique",
    slug: "mozambique",
    continent: "Africa",
    tagline: "Bazaruto Archipelago & Portuguese colonial charm",
    description: "Mozambique has its world class coral reefs, white sandy beaches, secluded islands, vibrant night life and the flagship reserve- Gorongosa Park. these are some of the reasons to visit the ‘PORTUGUESE GUINEA’.",
    highlights: ["Bazaruto Archipelago islands", "Whale shark snorkelling, Tofo", "Mozambique Island (UNESCO)", "Gorongosa National Park", "Pemba coastline"],
    experiences: ["Beach", "Wildlife", "Culture", "Adventure"],
    duration: "10–14 days",
    bestTime: "May – November",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Myanmar",
    slug: "myanmar",
    continent: "Asia",
    tagline: "Bagan's pagodas, Inle Lake & golden temples",
    description: "Myanmar with its stunning Stupas, impressive pagodas, unique culture, age old traditions, friendly people, amazing floating gardens, lakes are some of the few reasons to visit 'LAND OF THE GOLDEN PAGODA'.",
    highlights: ["Bagan pagoda sunrise balloon", "Inle Lake leg-rowing fishermen", "Shwedagon Pagoda, Yangon", "Mandalay Palace", "Kyaiktiyo Golden Rock"],
    experiences: ["Culture", "History", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "November – February",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Namibia",
    slug: "namibia",
    continent: "Africa",
    tagline: "Sossusvlei dunes, Etosha & the Skeleton Coast",
    description: "Namibia can claim limitless horizons, stark landscapes, untamed wilderness, beautiful coastline and the oldest living desert in the world. These are some of the reasons to visit the ‘LAND OF THE BRAVE’",
    highlights: ["Sossusvlei dunes & Deadvlei", "Etosha lion & elephant", "Skeleton Coast drive", "Fish River Canyon hike", "Himba village visit"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "12–16 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Nepal",
    slug: "nepal",
    continent: "Asia",
    tagline: "Everest base camp, Himalayan kingdoms & Buddhist monasteries",
    description: "Nepal is home to once in a life time treks & stunning Mt Everest. You can trek to the Everest base camp, learn the culture, admire the stupas, spot rhinos & tigers on a jungle safari & discover the heritage sites and lakes. These are some of the reasons to visit the ‘ROOF OF THE WORLD'",
    highlights: ["Everest Base Camp trek", "Annapurna panorama", "Kathmandu Durbar Square", "Chitwan rhino & elephant", "Pokhara lakeside sunrise"],
    experiences: ["Adventure", "Nature", "Culture", "History", "Wildlife"],
    duration: "12–18 days",
    bestTime: "October – November & March – May",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Netherlands",
    slug: "netherlands",
    continent: "Europe",
    tagline: "Tulip fields, windmills & Golden Age canals",
    description: "Netherlands has its Dutch Tulips, charming towns & villages, clogs, windmills, cheese, snacks and a great cycling destination. These are some of the reasons to visit this ‘KINGDOM OF LOW COUNTRIES’.",
    highlights: ["Keukenhof tulip fields (April)", "Amsterdam canal evening", "Rijksmuseum & Van Gogh Museum", "Windmills at Kinderdijk", "Delft blue pottery workshop"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "7–10 days",
    bestTime: "April – May & September",
    image: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "New Zealand",
    slug: "new-zealand",
    continent: "Oceania",
    tagline: "Fiordland, Hobbiton & Maori culture",
    description: "New Zealand will reward you with plenty of incredible attractions and local treasures. Experience the sublime landscapes, remarkable Maori culture, world famous vineyards and countless adventure activities. These are some of the reasons to visit the ‘LAND OF THE LONG WHITE CLOUD’.",
    highlights: ["Milford Sound cruise", "Hobbiton movie set", "Rotorua geothermal & Maori culture", "Queenstown bungy & adventure", "Abel Tasman sea kayak"],
    experiences: ["Nature", "Adventure", "Culture", "Wildlife", "Luxury"],
    duration: "14–21 days",
    bestTime: "December – March (South) | October – April (North)",
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Nicaragua",
    slug: "nicaragua",
    continent: "Central America",
    tagline: "Volcanoes, colonial cities & surf beaches",
    description: "Nicaragua has its gorgeous colonial cities, volcanoes perfect for adventure, pristine beaches, great wildlife and very friendly people. These are some of the reasons to visit this ‘LAND OF LAKES AND VOLCANOES’.",
    highlights: ["Granada colonial centre", "Volcano boarding, Cerro Negro", "Ometepe Island cycling", "León cathedral views", "San Juan del Sur beaches"],
    experiences: ["Adventure", "Culture", "Beach", "Nature"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Norway",
    slug: "norway",
    continent: "Europe",
    tagline: "Fjords, Northern lights & Viking heritage",
    description: "Norway was voted as the happiest place on Earth. It has its beautiful fjords, one of the best places to see Northern Lights, host of activities, numerous terrains & waterfalls to explore and rare wildlife. These are some of the reasons to visit the ‘LAND OF MIDNIGHT SUN”.",
    highlights: ["Geirangerfjord cruise", "Lofoten Islands drive", "Northern Lights, Tromsø", "Flåm Railway", "Bergen fish market"],
    experiences: ["Nature", "Adventure", "Culture", "History"],
    duration: "10–14 days",
    bestTime: "June – August (Fjords) | October – March (Aurora)",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Oman",
    slug: "oman",
    continent: "Middle East",
    tagline: "Wadis, desert forts & the Arabian Sea",
    description: "Oman is all about natural beauty, traditional culture & costumes, unique Omani food and friendly people. These are some of the reasons to visit ‘THE PEARL OF ARABIA’",
    highlights: ["Sultan Qaboos Grand Mosque", "Wadi Shab swimming", "Wahiba Sands desert camp", "Nizwa Fort & souk", "Mutrah Corniche"],
    experiences: ["Culture", "History", "Adventure", "Nature", "Luxury"],
    duration: "8–12 days",
    bestTime: "October – April",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Panama",
    slug: "panama",
    continent: "Central America",
    tagline: "The Canal, San Blas islands & cloud forests",
    description: "Panama is at the cross roads of two continents and two oceans. Experience & explore the Panama Canal the greatest engineering marvel, hub of bio diversity, numerous islands and an unique culture. These are some of the reasons to visit the ‘TRANSIT COUNTRY’.",
    highlights: ["Panama Canal Miraflores locks", "San Blas island community stay", "Boquete cloud forest hike", "Panama City Old Quarter", "Chiriqui River white water"],
    experiences: ["Culture", "Nature", "Adventure", "History", "Beach"],
    duration: "10–14 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518259102261-b40117eabbc9?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Paraguay",
    slug: "paraguay",
    continent: "South America",
    tagline: "Jesuit missions, wetlands & Guaraní culture",
    description: "Paraguay has its spectacular national parks, rare wildlife, unique local food & drink, outstanding hiking trails and traditional culture & markets. These are some of the reasons to visit ‘THE ISLAND SURROUNDED BY MAINLAND”.",
    highlights: ["Jesuit Missions of Trinidad", "Pantanal wetland wildlife", "Asunción historic centre", "Ybycuí National Park", "Rio Paraguay boat trip"],
    experiences: ["History", "Culture", "Wildlife", "Nature"],
    duration: "8–12 days",
    bestTime: "April – September",
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Peru",
    slug: "peru",
    continent: "South America",
    tagline: "Machu Picchu, Inca trails & Amazon headwaters",
    description: "Peru is one of the most diverse & dramatic countries in South America. Experience the spectacular land scape, rich biodiversity, adventure, ancient history, mysterious sites, living culture and impressive hospitality. These are some of the reasons to visit ‘THE LAND OF THE INCAS'.",
    highlights: ["Machu Picchu sunrise", "Sacred Valley of the Incas", "Lake Titicaca reed islands", "Amazon jungle lodge, Iquitos", "Lima food trail"],
    experiences: ["History", "Culture", "Adventure", "Nature", "Food"],
    duration: "12–18 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Philippines",
    slug: "philippines",
    continent: "Asia",
    tagline: "7,000+ islands, chocolate hills & whale sharks",
    description: "Philippines is the ultimate gataway to a paradise like destination. It is made up of more than 7000 islands with pristine white sandy beaches and is home to world renowned natural wonders. These are some of the reasons to visit the ‘TEXT CAPITAL OF THE WORLD’.",
    highlights: ["El Nido island hopping, Palawan", "Chocolate Hills, Bohol", "Whale shark swim, Cebu", "Banaue rice terraces", "Boracay White Beach"],
    experiences: ["Beach", "Nature", "Adventure", "Culture", "Wildlife"],
    duration: "12–18 days",
    bestTime: "November – May",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Poland",
    slug: "poland",
    continent: "Europe",
    tagline: "Kraków's old town, Auschwitz & Tatra mountains",
    description: "Poland is rich in history, well maintained UNESCO sites, diverse landscape, Polish Cuisine & Vodka famous world over and jaw dropping castles. These are some of the reasons to visit the ‘THE LAND OF POLANS’.",
    highlights: ["Kraków Old Town & Wawel", "Auschwitz-Birkenau memorial", "Warsaw Royal Route", "Wieliczka Salt Mine", "Tatra Mountains hiking"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "8–12 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1562874702-3f08a9a99d55?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1562874702-3f08a9a99d55?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Portugal",
    slug: "portugal",
    continent: "Europe",
    tagline: "Lisbon trams, Douro wine & Algarve cliffs",
    description: "Portugal is one of the great historical cities- with its UNESCO sites, wide cuisine, quality wines, vibrant nightlife and a huge variety of Flora and Fauna. These are some of the reasons to visit ‘REPUBLICA PORTUGUESA.",
    highlights: ["Lisbon tram & Belém Tower", "Douro Valley wine cruise", "Sintra romantic palaces", "Algarve sea cave kayak", "Porto ribeira riverside"],
    experiences: ["Culture", "Food", "Nature", "History", "Romance"],
    duration: "10–14 days",
    bestTime: "March – October",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Russia",
    slug: "russia",
    continent: "Europe",
    tagline: "Moscow's Kremlin, Trans-Siberian & Lake Baikal",
    description: "Russia is a magical country. It has its spectacular museums, charming cities, amazing natural wonders, impressive religious sites and the artful Moscow Metro. These are some of the reasons to visit the ‘LAND OF THE TSARS’.",
    highlights: ["Red Square & Kremlin, Moscow", "Hermitage Museum, St. Petersburg", "Trans-Siberian Railway", "Lake Baikal ice trek", "Bolshoi Theatre performance"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "14–21 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Serbia",
    slug: "serbia",
    continent: "Europe",
    tagline: "Belgrade nightlife, monasteries & Danube gorges",
    description: "Serbia is the Balkan nation where the East meets West. It has its history, vibrant nightlife, charming monasteries, bustling cities and old towns. These are some of the reasons to visit ‘MILICA”.",
    highlights: ["Belgrade fortress & Kalemegdan", "Drvengrad village (Kusturica)", "Iron Gates gorge cruise", "Studenica Monastery", "Novi Sad Petrovaradin fortress"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "7–10 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Seychelles",
    slug: "seychelles",
    continent: "Africa",
    tagline: "Giant tortoises, pristine beaches & granite boulders",
    description: "Seychelles has its stunning beaches, surprising wildlife, rugged mountains, verdant jungle, tasty creole cuisine and world class diving. These are some of the reasons to visit ‘ LAND OF PERPECTUAL SUMMER’.",
    highlights: ["Anse Source d'Argent, La Digue", "Giant tortoise sanctuary", "Vallée de Mai palm forest (UNESCO)", "Beau Vallon beach, Mahé", "Snorkelling off St. Anne"],
    experiences: ["Beach", "Luxury", "Romance", "Nature", "Wildlife"],
    duration: "8–12 days",
    bestTime: "April – May & October – November",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Singapore",
    slug: "singapore",
    continent: "Asia",
    tagline: "Garden city, hawker culture & world-class design",
    description: "Singapore’s varied charms are bound to enchant visitors. Indulge in world class eats, discover inspiring art every where, host of cultural events, party until and visit the countless attractions. These are some of the reasons to visit ‘THE LION CITY’.",
    highlights: ["Gardens by the Bay night show", "Maxwell Hawker Centre food trail", "Marina Bay Sands rooftop", "Chinatown & Little India", "Sentosa island resort"],
    experiences: ["Culture", "Food", "Luxury", "Nature"],
    duration: "5–7 days",
    bestTime: "February – April",
    image: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "South Africa",
    slug: "south-africa",
    continent: "Africa",
    tagline: "Big Five safaris, Cape Town & the Garden Route",
    description: "South Africa with its breath taking beaches, abundance wild life & activities, superb food & wine, friendly people & cultures, near perfect weather, rich history are some of the reasons to visit this 'RAINBOW NATION'.",
    highlights: ["Kruger safari game drives", "Table Mountain cable car", "Cape Peninsula drive", "Stellenbosch wine tour", "Drakensberg hike"],
    experiences: ["Wildlife", "Nature", "Culture", "Food", "Adventure", "Luxury"],
    duration: "14–21 days",
    bestTime: "May – September (Safari) | November – March (Cape)",
    image: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "South Korea",
    slug: "south-korea",
    continent: "Asia",
    tagline: "K-culture, palace temples & mountain shrines",
    description: "South Korea is a small country with diverse landscapes, colorful cultures and traditions. Explore and Experience its wonderful architecture, delicious Korean cuisine, breathtaking nature, vibrant night life and rich culture. These are some of the reasons to visit ‘THE LAND OF THE MORNING CALM”.",
    highlights: ["Gyeongbokgung Palace in hanbok", "Bukchon Hanok Village, Seoul", "Jeju Island volcanic landscape", "Haeinsa Buddhist temple stay", "DMZ border zone visit"],
    experiences: ["Culture", "History", "Nature", "Food"],
    duration: "10–14 days",
    bestTime: "March – May & September – November",
    image: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Spain",
    slug: "spain",
    continent: "Europe",
    tagline: "Gaudí, flamenco, Alhambra & pintxos",
    description: "Spain is truly an incredible country. It has its awe inspiring landscapes, host of adventure activities, unique festivals & events, classy museums and enchanting islands. These are some of the reasons to visit ‘HISPANIA’.",
    highlights: ["Sagrada Família & Park Güell", "Alhambra at dusk, Granada", "Prado Museum, Madrid", "San Sebastián food tour", "Flamenco performance, Seville"],
    experiences: ["Culture", "History", "Food", "Romance", "Luxury"],
    duration: "12–16 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Sri Lanka",
    slug: "sri-lanka",
    continent: "Asia",
    tagline: "Sigiriya, tea country & golden beaches",
    description: "Sri Lanka with its pristine coastline & beaches, close encounters with whales, gorgeous land scape, Buddhist heritage and highest density of Leopards in the world are some of the reasons to visit this magical island.",
    highlights: ["Sigiriya rock fortress climb", "Yala leopard safari", "Ella train journey", "Kandy Perahera festival", "Mirissa whale watching"],
    experiences: ["History", "Wildlife", "Nature", "Culture", "Beach"],
    duration: "10–14 days",
    bestTime: "November – April",
    image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Sweden",
    slug: "sweden",
    continent: "Europe",
    tagline: "Ice hotels, Midnight Sun & Viking heritage",
    description: "Sweden is all about nature- mountains, lakes and 29 National Parks. Explore and experience its castles, unique culture, architecture and host of activities. These are some of the reasons to visit ‘THE ELONGATED COUNTRY’.",
    highlights: ["ICEHOTEL, Jukkasjärvi", "Stockholm archipelago boat", "ABBA Museum, Stockholm", "Gamla Uppsala Viking burial mounds", "Midnight Sun in Lapland"],
    experiences: ["Culture", "Adventure", "Nature", "History", "Luxury"],
    duration: "8–12 days",
    bestTime: "June – August (Midnight Sun) | December – March (Aurora)",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Switzerland",
    slug: "switzerland",
    continent: "Europe",
    tagline: "Alpine peaks, chocolate & luxury trains",
    description: "Switzerland is by far the best choice for holidaying. It has its Swiss Alps, incredible natural beauty, fairy tale castles, gorgeous water falls & Lakes and an efficient transport system. These are some of the reasons to visit ‘HELVETIA’.",
    highlights: ["Matterhorn & Zermatt", "Jungfraujoch top of Europe", "Glacier Express train", "Lucerne Chapel Bridge", "Lake Geneva sunset"],
    experiences: ["Nature", "Luxury", "Adventure", "Romance", "Culture"],
    duration: "10–14 days",
    bestTime: "June – September & December – March",
    image: "https://images.unsplash.com/photo-1527434762461-6f0c5c5b4c7e?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1527434762461-6f0c5c5b4c7e?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tanzania",
    slug: "tanzania",
    continent: "Africa",
    tagline: "Serengeti, Kilimanjaro & Zanzibar beaches",
    description: "Tanzania is well known for its incredible game reserves teeming with wildlife to glorious beaches, luxurious accommodation and amazing culture & food.",
    highlights: ["Great Migration, Serengeti", "Ngorongoro Crater game drive", "Kilimanjaro summit trek", "Zanzibar Stone Town", "Mahale chimpanzee trek"],
    experiences: ["Wildlife", "Adventure", "Nature", "Beach", "Culture"],
    duration: "14–21 days",
    bestTime: "June – October (Migration) | December – March (Beach)",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Thailand",
    slug: "thailand",
    continent: "Asia",
    tagline: "Temples, floating markets & Andaman islands",
    description: "Thailand is well known for its delicious & diverse cuisine, friendly people, vibrant nightlife, pristine beaches, host of activities, magical temples & floating & night markets. These are some of the reasons to visit this ‘ Land of Smiles’.",
    highlights: ["Grand Palace & Wat Phra Kaew", "Chiang Mai elephant sanctuary", "Phang Nga Bay sea kayak", "Floating market, Damnoen Saduak", "Full Moon Party or quiet Koh Lanta"],
    experiences: ["Culture", "Beach", "Nature", "Food", "Adventure"],
    duration: "10–16 days",
    bestTime: "November – March",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tibet",
    slug: "tibet",
    continent: "Asia",
    tagline: "Potala Palace, monastery stays & the Roof of the World",
    description: "Tibet is a religious and mysterious place. Experience the breathtaking natural beauty, spiritual monasteries & temples, hospitable local Tibetans, interesting festivals and activities. These are some of the reasons to visit ‘THE ROOF OF THE WORLD’",
    highlights: ["Potala Palace, Lhasa", "Jokhang Temple pilgrims", "Lake Namtso at 4,718m", "Monastery of Tashilhunpo", "Everest Base Camp (Tibet side)"],
    experiences: ["Culture", "History", "Adventure", "Nature"],
    duration: "10–14 days",
    bestTime: "April – October",
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Tunisia",
    slug: "tunisia",
    continent: "Africa",
    tagline: "Carthage, Sahara villages & Mediterranean beaches",
    description: "Tunisia has its fascinating sandy beaches, grand ancient ruins, rolling dunes of the Sahara, fascinating archaeological sites and charming historical towns. These are some of the reasons to visit ‘IFRIQIYYAH’.",
    highlights: ["Carthage ruins", "Sahara jeep tour", "Sidi Bou Saïd village", "Bardo Museum mosaics", "Djerba island"],
    experiences: ["History", "Culture", "Adventure", "Beach"],
    duration: "8–12 days",
    bestTime: "March – June & September – November",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Turkey",
    slug: "turkey",
    continent: "Asia",
    tagline: "Cappadocia balloons, Hagia Sophia & turquoise coast",
    description: "Turkey with its archaeological sites, Turkish baths, beautiful beaches, amazing food, excellent museums, bargain shopping, natural wonders & unique architecture are some of the reasons to visit this unique country.",
    highlights: ["Hot air balloon, Cappadocia", "Hagia Sophia & Blue Mosque, Istanbul", "Grand Bazaar & Bosphorus cruise", "Ruins of Ephesus", "Turquoise Coast gulet cruise"],
    experiences: ["History", "Culture", "Adventure", "Beach", "Food", "Romance"],
    duration: "10–16 days",
    bestTime: "April – May & September – October",
    image: "https://images.unsplash.com/photo-1545631757-4f36af74c1de?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1545631757-4f36af74c1de?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Uganda",
    slug: "uganda",
    continent: "Africa",
    tagline: "Gorilla trekking, Bwindi & the Nile source",
    description: "Uganda boasts a varied and thriving landscape that is home to an abundance of rare and exotic wildlife. Go in search of elusive chimp in tropical rainforests and observe giant Gorilla in its natural habitat. These are some of the reasons to visit the ‘PEARL OF AFRICA’.",
    highlights: ["Gorilla trekking, Bwindi", "Chimpanzee track, Kibale", "White-water rafting, Nile Jinja", "Tree-climbing lions, Queen Elizabeth NP", "Source of the Nile"],
    experiences: ["Wildlife", "Nature", "Adventure", "Culture"],
    duration: "10–14 days",
    bestTime: "June – September & December – February",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Ukraine",
    slug: "ukraine",
    continent: "Europe",
    tagline: "Kyiv's golden domes, Lviv cafés & Carpathians",
    description: "Ukraine has its amazing nature, peculiar traditions, ancient architecture, endless historical churches, charming old towns and villages. These are some of the reasons to visit ‘ THE BREAD BASKET OF EUROPE’.",
    highlights: ["Kyiv Pechersk Lavra monastery", "Lviv Old Town & cafés", "Carpathian Mountain hiking", "Chernobyl exclusion zone tour", "Odessa Potemkin Steps"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "10–14 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "United Kingdom",
    slug: "united-kingdom",
    continent: "Europe",
    tagline: "Castles, Highlands & cultural London",
    description: "United Kingdom is well known world over for its massive palaces & castles, most beautiful parks and gardens, spectacular natural beauty, jaw dropping museums and wide array of festivals and events. These are some of the reasons to visit this ‘MAGICAL KINGDOM’",
    highlights: ["Tower of London & Buckingham Palace", "Scottish Highlands & Loch Ness", "Stonehenge at dawn", "Oxford & Blenheim Palace", "Lake District walking"],
    experiences: ["History", "Culture", "Nature", "Adventure"],
    duration: "12–16 days",
    bestTime: "May – September",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Uzbekistan",
    slug: "uzbekistan",
    continent: "Asia",
    tagline: "Silk Road cities, turquoise domes & desert caravans",
    description: "Uzbekistan is recognized by its dazzling mosques, intricately carved minarets and Soviet style buildings and towns stuck in time. Travel through the silk routes, explore the UNESCO world heritage towns, go shopping and spend a night in a yurt camp. These are some of the reasons to explore this beautiful landlocked country.",
    highlights: ["Registan Square, Samarkand", "Khiva walled city", "Bukhara historic centre", "Aral Sea expedition", "Ferghana Valley silk workshops"],
    experiences: ["History", "Culture", "Adventure", "Nature"],
    duration: "10–14 days",
    bestTime: "April – June & September – October",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Vietnam",
    slug: "vietnam",
    continent: "Asia",
    tagline: "Ha Long Bay, lantern-lit Hội An & Saigon streets",
    description: "Vietnam is one of the few destinations that encompass incredible scenery, breathtaking landscape, heroic history, traditional festivals, unique culture and friendly & hospitable people. It’s fascinating history is one of war, colonization and rebellion.",
    highlights: ["Ha Long Bay cruise", "Hội An lantern night", "Huế Imperial Citadel", "Mỹ Sơn Hindu ruins", "Sapa rice terrace trek"],
    experiences: ["Culture", "History", "Nature", "Food", "Adventure"],
    duration: "12–18 days",
    bestTime: "February – April & August – October",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "West Indies",
    slug: "west-indies",
    continent: "Caribbean",
    tagline: "Cricket, rum, carnival & Caribbean beaches",
    description: "West indies or the Caribbean islands is there in everyone’ s bucket list. It has the pristine beaches, wide choice of accommodation, rich cultural diversity, vibrant nightlife, fine culture and extremely warm & friendly people.",
    highlights: ["Barbados rum distillery tour", "Trinidad Carnival", "St. Lucia Pitons hike", "Tobago reef snorkelling", "Grenadines sailing"],
    experiences: ["Beach", "Culture", "Adventure", "Nature", "Food"],
    duration: "10–16 days",
    bestTime: "December – April",
    image: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1544979590-37e9b47eb705?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Zambia",
    slug: "zambia",
    continent: "Africa",
    tagline: "Victoria Falls & walking safaris in South Luangwa",
    description: "Zambia the hidden Gem. Explore and experience the majestic Victoria Falls, take a game drive in various parks teeming with wildlife. Good reasons to visit this ‘AIR CONDITIONED STATE’",
    highlights: ["Victoria Falls (Zambia side)", "South Luangwa walking safari", "Lower Zambezi canoe safari", "Kafue National Park", "Royal Livingstone experience"],
    experiences: ["Wildlife", "Adventure", "Nature", "Luxury"],
    duration: "10–14 days",
    bestTime: "June – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
  {
    name: "Zimbabwe",
    slug: "zimbabwe",
    continent: "Africa",
    tagline: "Victoria Falls, Hwange lions & Great Zimbabwe ruins",
    description: "Zimbabwe’s National Parks are amongst the finest in Africa. Get mesmerized by the majestic Victoria Falls, take game drives in diverse national parks, relax on the shores of Lake Kariba and immerse yourself in the unique sites. These are some of the reasons to visit this 'JEWEL OF AFRICA'",
    highlights: ["Victoria Falls spray walk", "Hwange elephant herds", "Great Zimbabwe ruins", "Matobo Hills rhino trek", "Canoe safari, Zambezi"],
    experiences: ["Wildlife", "History", "Nature", "Adventure"],
    duration: "10–16 days",
    bestTime: "May – October",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1920&q=80",
  },
];

// ── Merge real scraped catalog images over the editorial data ──
// Every editorial destination gets its actual 365tours.in photos, flag and regions.
// The card/hero images are switched from stock photos to the real gallery shots.
for (const dest of destinations) {
  const entry = catalog[dest.slug];
  if (!entry) continue;
  dest.id = entry.id;
  dest.gallery = entry.gallery;
  dest.flag = entry.flag || undefined;
  dest.regions = entry.regions;
  dest.itineraries = entry.itineraries;
  dest.recipeImage = entry.recipeImage || undefined;
  if (entry.gallery.length > 0) {
    dest.image = entry.gallery[0];
    // Hero uses the destination's real main_image banner (as on 365tours.in),
    // falling back to the first gallery photo if it's ever missing.
    dest.heroImage = entry.mainImage || entry.gallery[0];
  }
}

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export function getAllSlugs(): string[] {
  return destinations.map((d) => d.slug);
}
