// Per-state hero photo, tagline, and itinerary breakdown for /india/[state] pages.
// Sourced from the live 365tours.in/India destination-detail pages.
export interface IndiaStateItinerary {
  src: string;
  days: string;
  places: string[];
}

export interface IndiaStateDetail {
  slug: string;
  name: string;
  tagline: string;
  heroImage: string | null;
  itineraries: IndiaStateItinerary[];
}

export const indiaStateDetails: Record<string, IndiaStateDetail> = {
  "andaman": {
    slug: "andaman",
    name: "Andaman",
    tagline: "LEGENDARY BEAUTY",
    heroImage: "/india/states/andaman/hero.jpg",
    itineraries: [
      { src: "/india/states/andaman/tour-1.jpg", days: "4 Days", places: ["Port Blair"] },
      { src: "/india/states/andaman/tour-2.jpg", days: "5 Days", places: ["Havelock", "Port Blair"] },
      { src: "/india/states/andaman/tour-3.jpg", days: "6 Days", places: ["Port Blair", "Havelock"] },
      { src: "/india/states/andaman/tour-4.jpg", days: "7 Days", places: ["Neil", "Havelock", "Port Blair"] },
      { src: "/india/states/andaman/tour-5.jpg", days: "8 Days", places: ["Diglipur", "Neil", "Havelock", "Port Blair"] },
      { src: "/india/states/andaman/tour-6.jpg", days: "10 Days", places: ["Baratang island", "Neil", "Havelock", "Port Blair"] },
      { src: "/india/states/andaman/tour-7.jpg", days: "10 Days", places: ["Scuba Diving Package", "Port Blair", "Havelock"] },
      { src: "/india/states/andaman/tour-8.jpg", days: "11 Days", places: ["Barren Island", "Elephant Beach", "Baratang island", "Diglipur", "Radhanagar Beach", "Neil Island", "North Bay", "Havelock Island", "Port Blair"] },
    ],
  },
  "andhra-pradesh": {
    slug: "andhra-pradesh",
    name: "Andhra Pradesh",
    tagline: "THE MORE YOU SEE IT, THE MORE YOU LOVE IT",
    heroImage: "/india/states/andhra-pradesh/hero.jpg",
    itineraries: [
      { src: "/india/states/andhra-pradesh/tour-1.jpg", days: "2-4 Days", places: ["Visakhpatnam", "Araku"] },
      { src: "/india/states/andhra-pradesh/tour-2.jpg", days: "2-4 Days", places: ["Vijayawada", "Srisailam"] },
      { src: "/india/states/andhra-pradesh/tour-3.jpg", days: "2-4 Days", places: ["Vijayawada", "Konaseema"] },
      { src: "/india/states/andhra-pradesh/tour-4.jpg", days: "2-3 Days", places: ["Kurnool", "Ex Hyderabad"] },
      { src: "/india/states/andhra-pradesh/tour-5.jpg", days: "1-2 Days", places: ["Lepakshi", "Ex Bangalore"] },
      { src: "/india/states/andhra-pradesh/tour-6.jpg", days: "3-5 Days", places: ["Hyderabad"] },
      { src: "/india/states/andhra-pradesh/tour-7.jpg", days: "1-2 Days", places: ["Tirupati", "Ex Chennai", "Ex Bangalore"] },
      { src: "/india/states/andhra-pradesh/tour-8.jpg", days: "2-3 Days", places: ["Kakinada", "Konaseema"] },
    ],
  },
  "bihar": {
    slug: "bihar",
    name: "Bihar",
    tagline: "VISIT AND BE INSPIRED",
    heroImage: "/india/states/bihar/hero.jpg",
    itineraries: [
      { src: "/india/states/bihar/tour-1.jpg", days: "3-5 Days", places: ["Patna", "Nalanda"] },
      { src: "/india/states/bihar/tour-2.jpg", days: "2-4 Days", places: ["Bodh Gaya"] },
      { src: "/india/states/bihar/tour-3.jpg", days: "4-6 Days", places: ["Patna", "Nalanda", "Bodh Gaya"] },
      { src: "/india/states/bihar/tour-4.jpg", days: "4-7 Days", places: ["Sasaram", "Patna", "Nalanda", "Bodh Gaya"] },
      { src: "/india/states/bihar/tour-5.jpg", days: "3-4 Days", places: ["Patna", "Gaya"] },
      { src: "/india/states/bihar/tour-6.jpg", days: "3-4 Days", places: ["Vaishali", "Patna", "Nalanda"] },
      { src: "/india/states/bihar/tour-7.jpg", days: "4-5 Days", places: ["Munger", "Bhimbandh Sanctuary", "Patna"] },
      { src: "/india/states/bihar/tour-8.jpg", days: "4-5 Days", places: ["Rajgir", "Nalanda", "Patna", "Bodh Gaya"] },
    ],
  },
  "chhattisgarh": {
    slug: "chhattisgarh",
    name: "Chhattisgarh",
    tagline: "THE LAND OF SURPRISES",
    heroImage: "/india/states/chhattisgarh/hero.jpg",
    itineraries: [
      { src: "/india/states/chhattisgarh/tour-1.jpg", days: "5 Days", places: ["Raipur", "Champaran", "Bharamdeo"] },
      { src: "/india/states/chhattisgarh/tour-2.jpg", days: "6 Days", places: ["Raipur", "Jagdalpur", "Kanger Valley", "Chitrakote Falls"] },
      { src: "/india/states/chhattisgarh/tour-3.jpg", days: "4 Days", places: ["Barnawapara", "Raipur"] },
      { src: "/india/states/chhattisgarh/tour-4.jpg", days: "4 Days", places: ["Bharamdeo", "Baiga Tribal Village", "Raipur"] },
      { src: "/india/states/chhattisgarh/tour-5.jpg", days: "3-7 Days", places: ["Raipur", "Achanakmar Tiger Reserve", "Pench", "Kanha", "Bandhavgarh"] },
      { src: "/india/states/chhattisgarh/tour-6.jpg", days: "7 Days", places: ["Baiga Tribal Village", "Bilaspur", "Tala", "Baranawapara sanctuary"] },
      { src: "/india/states/chhattisgarh/tour-7.jpg", days: "8 Days", places: ["Bilaspur", "Baranawapara sanctuary", "Siripur", "Kanker Palace", "Jagdalpur", "Chitrakote Waterfall", "Raipur"] },
      { src: "/india/states/chhattisgarh/tour-8.jpg", days: "5 Days", places: ["Bilaspur", "Pali", "Ratnapur", "Raipur"] },
    ],
  },
  "new-delhi": {
    slug: "new-delhi",
    name: "New Delhi",
    tagline: "IMPERIAL SPLENDOUR",
    heroImage: "/india/states/new-delhi/hero.jpg",
    itineraries: [
      { src: "/india/states/new-delhi/tour-1.jpg", days: "4-7 Days", places: ["City Break"] },
      { src: "/india/states/new-delhi/tour-2.jpg", days: "2-4 Days", places: ["Short Break", "Ex New Delhi", "Haridwar", "Rishikesh"] },
      { src: "/india/states/new-delhi/tour-3.jpg", days: "2-4 Days", places: ["Short Break", "Ex New Delhi", "Agra", "Vrindavan", "Mathura"] },
      { src: "/india/states/new-delhi/tour-4.jpg", days: "2-4 Days", places: ["Short Break", "Ex New Delhi", "Jim Corbett NP"] },
      { src: "/india/states/new-delhi/tour-5.jpg", days: "Short Break", places: ["Ex New Delhi", "Sarsika Sanctuary", "Bharatpur Sanctuary"] },
      { src: "/india/states/new-delhi/tour-6.jpg", days: "Short Break", places: ["Ex New Delhi", "Landsdowne", "Mussoorie"] },
      { src: "/india/states/new-delhi/tour-7.jpg", days: "Short Break", places: ["Ex New Delhi", "Jaipur", "Neemrana"] },
      { src: "/india/states/new-delhi/tour-8.jpg", days: "Short Break", places: ["Ex New Delhi", "Nainital"] },
    ],
  },
  "goa": {
    slug: "goa",
    name: "Goa",
    tagline: "A PERFECT HOLIDAY DESTINATION",
    heroImage: "/india/states/goa/hero.jpg",
    itineraries: [
      { src: "/india/states/goa/tour-1.jpg", days: "Heritage Goa", places: ["Basilica of Bom Jesus", "Se Cathedral Church", "St Estevam Island", "St Francis of Assisi"] },
      { src: "/india/states/goa/tour-2.jpg", days: "Forts of Goa", places: ["Aguada", "Reis Magos Fort", "Cabo Re Rama", "Corjuem", "Tiracol", "Sinquerim", "Mormugao"] },
      { src: "/india/states/goa/tour-3.jpg", days: "Beaches of Goa", places: ["Majorda", "Candolim", "Calangute", "Arambol", "Anjuna"] },
      { src: "/india/states/goa/tour-4.jpg", days: "Wild Life Sanctuaries", places: ["Bondia", "Cotigao", "Dr Sailm Ali Bird sanctuary", "Mahavir", "Dudh Sagar"] },
      { src: "/india/states/goa/tour-5.jpg", days: "Casino Packages", places: ["Deltin Royale", "Casino Carnival", "Casino Palms", "Casino Paradise", "Crown Casino"] },
      { src: "/india/states/goa/tour-6.jpg", days: "Water Activities", places: ["Parasailing", "Jet Skiing", "Kayaking", "Scuba Diving", "Snorkelling"] },
      { src: "/india/states/goa/tour-7.jpg", days: "Adventure", places: ["White Water Rafting", "Knee Boarding", "Bungee jumping", "ATV Biking", "Zorbing"] },
      { src: "/india/states/goa/tour-8.jpg", days: "Off the beaten path", places: ["Butterfly conservatory", "Spice plantations", "Devil’s Canyon", "Goan Caves", "Spice plantations"] },
    ],
  },
  "gujarat": {
    slug: "gujarat",
    name: "Gujarat",
    tagline: "ONE STATE. INFINITE EXPERIENCES",
    heroImage: "/india/states/gujarat/hero.jpg",
    itineraries: [
      { src: "/india/states/gujarat/tour-1.jpg", days: "3-4 Days", places: ["Ahmedabad", "Vadodara", "Statue of Unity"] },
      { src: "/india/states/gujarat/tour-3.jpg", days: "5- 6 Days", places: ["Dwarka", "Porbandar", "Somnath", "Gir NP"] },
      { src: "/india/states/gujarat/tour-4.jpg", days: "3-5 Days", places: ["Rann of Kutch"] },
      { src: "/india/states/gujarat/tour-5.jpg", days: "Union Territories", places: ["Dadra & Nagar Haveli", "Diu", "Daman"] },
      { src: "/india/states/gujarat/tour-6.jpg", days: "4-5 Days", places: ["Thol Sanctuary", "Adalaj Stepwell", "Ahmedabad", "Vadodara"] },
      { src: "/india/states/gujarat/tour-7.jpg", days: "4-5 Days", places: ["Lothal", "Ahmedabad", "Vadodara"] },
      { src: "/india/states/gujarat/tour-8.jpg", days: "4-5 Days", places: ["Champaner", "Ahmedabad", "Vadodara"] },
    ],
  },
  "himachal-pradesh": {
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    tagline: "THE LAND OF GODS",
    heroImage: "/india/states/himachal-pradesh/hero.jpg",
    itineraries: [
      { src: "/india/states/himachal-pradesh/tour-1.jpg", days: "4-7 Days", places: ["Shimla", "Mashobra", "Kufri", "Chail"] },
      { src: "/india/states/himachal-pradesh/tour-2.jpg", days: "4 Days", places: ["Dalhousie", "Dharamshala"] },
      { src: "/india/states/himachal-pradesh/tour-3.jpg", days: "4-6 Days", places: ["Manali", "Rohtang Pass", "Kullu"] },
      { src: "/india/states/himachal-pradesh/tour-4.jpg", days: "6-8 Days", places: ["Khajjar", "Chamba", "Dalhouse", "Dharamshala"] },
      { src: "/india/states/himachal-pradesh/tour-5.jpg", days: "4 Days", places: ["Dharamshala", "Mcleodganj"] },
      { src: "/india/states/himachal-pradesh/tour-6.jpg", days: "10 Days", places: ["Manali", "Kullu", "Rohtang Pass", "Shimla", "Chail", "Kufri"] },
      { src: "/india/states/himachal-pradesh/tour-7.jpg", days: "4-7 Days", places: ["Spiti Valley", "Chandratal Lake", "Pin Valley"] },
      { src: "/india/states/himachal-pradesh/tour-8.jpg", days: "3 Days", places: ["Palampur"] },
    ],
  },
  "jammu-and-kashmir": {
    slug: "jammu-and-kashmir",
    name: "Jammu & Kashmir",
    tagline: "PARADISE ON EARTH",
    heroImage: "/india/states/jammu-and-kashmir/hero.jpg",
    itineraries: [
      { src: "/india/states/jammu-and-kashmir/tour-1.jpg", days: "1-2 Days", places: ["Vaishno Devi", "Jammu"] },
      { src: "/india/states/jammu-and-kashmir/tour-2.jpg", days: "City Break", places: ["Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-3.jpg", days: "Mini Break", places: ["Gulmarg", "Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-4.jpg", days: "Short Break", places: ["Pahalgam", "Gulmarg", "Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-5.jpg", days: "Big Break", places: ["Sonamarg", "Pahalgam", "Gulmarg", "Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-6.jpg", days: "Long Break", places: ["Patnitop", "Sonamarg", "Pahalgam", "Gulmarg", "Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-7.jpg", days: "Deluxe Kashmir", places: ["Aru Valley", "Patnitop", "Sonamarg", "Pahalgam", "Gulmarg", "Srinagar"] },
      { src: "/india/states/jammu-and-kashmir/tour-8.jpg", days: "Classic Kashmir", places: ["Yusmarg", "Aru Valley", "Patnitop", "Sonamarg", "Pahalgam", "Gulmarg", "Srinagar"] },
    ],
  },
  "jharkhand": {
    slug: "jharkhand",
    name: "Jharkhand",
    tagline: "NATURE’S HIDDEN JEWEL",
    heroImage: "/india/states/jharkhand/hero.jpg",
    itineraries: [
      { src: "/india/states/jharkhand/tour-1.jpg", days: "Waterfalls", places: ["Ghaghari Dham", "Sita Fall", "Johna Falls", "Chandil Dam", "Lodh Falls"] },
      { src: "/india/states/jharkhand/tour-2.jpg", days: "Religious", places: ["Luguburu Ghantbari", "Bokaro"] },
      { src: "/india/states/jharkhand/tour-3.jpg", days: "Adventure", places: ["Trekking", "Aerosports, Hot Air Balloon, Water Sports", "Parasailing"] },
      { src: "/india/states/jharkhand/tour-4.jpg", days: "Eco Tourism", places: ["Patratu Valley", "Chuttupallu Valley", "Hargaddi Chokahatu", "Khutabandh"] },
      { src: "/india/states/jharkhand/tour-5.jpg", days: "Heritage", places: ["Tanginath", "Faashi Taalab", "Dalma Hill Top", "Navratn Garh"] },
      { src: "/india/states/jharkhand/tour-6.jpg", days: "City Break", places: ["Jamshedpur"] },
      { src: "/india/states/jharkhand/tour-7.jpg", days: "National Parks", places: ["Betla", "Dalma", "Hazaribagh", "Udhwa", "Singhbhum"] },
      { src: "/india/states/jharkhand/tour-8.jpg", days: "City Break", places: ["Ranchi"] },
    ],
  },
  "kerala": {
    slug: "kerala",
    name: "Kerala",
    tagline: "GOD’S OWN COUNTRY",
    heroImage: "/india/states/kerala/hero.jpg",
    itineraries: [
      { src: "/india/states/kerala/tour-1.jpg", days: "4-7 Days", places: ["Kochi", "Thattekad Sanctuary", "Vazachai Falls"] },
      { src: "/india/states/kerala/tour-2.jpg", days: "4-7 Days", places: ["Thiruvanthapuram", "Kovalam", "Varkala"] },
      { src: "/india/states/kerala/tour-3.jpg", days: "4-7 Days", places: ["Munnar", "Eravikulam NP", "Anamudi", "Chinnar", "Thekkady"] },
      { src: "/india/states/kerala/tour-4.jpg", days: "4-6 Days", places: ["Kumarakom", "Alappuzha"] },
      { src: "/india/states/kerala/tour-5.jpg", days: "4-5 Days", places: ["Wayanad"] },
      { src: "/india/states/kerala/tour-6.jpg", days: "3-5 Days", places: ["Thrissur", "Athirappilly Falls", "Guruvayoor"] },
      { src: "/india/states/kerala/tour-7.jpg", days: "3-5 Days", places: ["Kollam", "Ashtamudi"] },
      { src: "/india/states/kerala/tour-8.jpg", days: "3-5 Days", places: ["Lakshadweep"] },
    ],
  },
  "karnataka": {
    slug: "karnataka",
    name: "Karnataka",
    tagline: "ONE STATE. MANY WORLDS",
    heroImage: "/india/states/karnataka/hero.jpg",
    itineraries: [
      { src: "/india/states/karnataka/tour-1.jpg", days: "3-7 Days", places: ["Mysuru", "Srirangapatna", "Nagarhole", "Kabini", "Ranganathittu"] },
      { src: "/india/states/karnataka/tour-2.jpg", days: "3-5 Days", places: ["Coorg"] },
      { src: "/india/states/karnataka/tour-3.jpg", days: "3-7 Days", places: ["Hampi", "Badami", "Pattadakal"] },
      { src: "/india/states/karnataka/tour-4.jpg", days: "3-6 Days", places: ["Chickmagalur", "Kudremukh"] },
      { src: "/india/states/karnataka/tour-5.jpg", days: "3-5 Days", places: ["Hassan", "Shravanabelagola", "Belur", "Gorur", "Manjarabad Fort", "Halebid", "Koravangala"] },
      { src: "/india/states/karnataka/tour-6.jpg", days: "3-6 Days", places: ["Mangalore", "Udupi", "Sringeri", "Sultan Battery", "Jog Falls"] },
      { src: "/india/states/karnataka/tour-7.jpg", days: "Weekend Breaks", places: ["Ex Bengaluru", "Kanakpura", "Sakleshpur", "Bheemeshwari", "Shivanasamudra Falls"] },
      { src: "/india/states/karnataka/tour-8.jpg", days: "3-4 Days", places: ["Shimoga", "Agumbe", "Jog Falls"] },
    ],
  },
  "maharashtra": {
    slug: "maharashtra",
    name: "Maharashtra",
    tagline: "A CULMINATION OF CULTURE & HERITAGE",
    heroImage: "/india/states/maharashtra/hero.jpg",
    itineraries: [
      { src: "/india/states/maharashtra/tour-1.jpg", days: "Weekend Breaks", places: ["Ex Mumbai", "Lonavala", "Kolad", "Igatpuri", "Matheran"] },
      { src: "/india/states/maharashtra/tour-2.jpg", days: "Weekend Breaks", places: ["Ex Pune", "Rajmachi", "Panchgani", "Andharban", "Junnar", "Satar"] },
      { src: "/india/states/maharashtra/tour-3.jpg", days: "2-4 Days", places: ["Shirdi", "Shani Shingnapur", "Ahmednagar"] },
      { src: "/india/states/maharashtra/tour-4.jpg", days: "3-5 Days", places: ["Aurangabad", "Ajanta", "Ellora"] },
      { src: "/india/states/maharashtra/tour-5.jpg", days: "3-5 Days", places: ["Nashik", "Ramkund", "Dudhsagar", "Trimbakeshwar"] },
      { src: "/india/states/maharashtra/tour-6.jpg", days: "2-5 Days", places: ["Kolhapur", "Panhala", "Rajmachi"] },
      { src: "/india/states/maharashtra/tour-7.jpg", days: "2-3 Days", places: ["Pandharpur"] },
      { src: "/india/states/maharashtra/tour-8.jpg", days: "3-4 Days", places: ["Ganapatipule"] },
    ],
  },
  "madhya-pradesh": {
    slug: "madhya-pradesh",
    name: "Madhya Pradesh",
    tagline: "THE HEART OF INCREDIBLE INDIA",
    heroImage: "/india/states/madhya-pradesh/hero.jpg",
    itineraries: [
      { src: "/india/states/madhya-pradesh/tour-1.jpg", days: "4-7 Days", places: ["Bhopal", "Sanchi", "Bhimbetka", "Panchmarhi"] },
      { src: "/india/states/madhya-pradesh/tour-2.jpg", days: "2-6 Days", places: ["National Parks", "Panna", "Rewa", "Kanha", "Tawa", "Bandhavgarh", "Parsili", "Pench"] },
      { src: "/india/states/madhya-pradesh/tour-3.jpg", days: "4-7 Days", places: ["Gwalior", "Orchha", "Morena", "Shivpuri"] },
      { src: "/india/states/madhya-pradesh/tour-4.jpg", days: "3-7 Days", places: ["Jabalpur", "Bheda Ghat", "Mandia", "Bargi Hills"] },
      { src: "/india/states/madhya-pradesh/tour-5.jpg", days: "3-7 Days", places: ["Indore", "Omkareshwar", "Ujjain", "Maheshwar"] },
      { src: "/india/states/madhya-pradesh/tour-6.jpg", days: "6-8 Days", places: ["Tawa", "Madhai", "Panchmarhi", "Bhopal"] },
      { src: "/india/states/madhya-pradesh/tour-7.jpg", days: "6-8 Days", places: ["Indore", "Janapav Hill", "Mandu", "Maheshwar", "Sailani island"] },
      { src: "/india/states/madhya-pradesh/tour-8.jpg", days: "3-4 Days", places: ["Khajuraho"] },
    ],
  },
  "odisha": {
    slug: "odisha",
    name: "Odisha",
    tagline: "SCENIC, SERENE, SUBLIME",
    heroImage: "/india/states/odisha/hero.jpg",
    itineraries: [
      { src: "/india/states/odisha/tour-1.jpg", days: "4-6 Days", places: ["Bhubaneshwar", "Konark", "Puri"] },
      { src: "/india/states/odisha/tour-2.jpg", days: "3-4 Days", places: ["Gopalpur on Sea"] },
      { src: "/india/states/odisha/tour-3.jpg", days: "3-5 Days", places: ["Daringbadi"] },
      { src: "/india/states/odisha/tour-4.jpg", days: "3-5 Days", places: ["Bhitarkanika National Park"] },
      { src: "/india/states/odisha/tour-5.jpg", days: "3-4 Days", places: ["Simlipal National Park"] },
      { src: "/india/states/odisha/tour-6.jpg", days: "3-5 Days", places: ["Chilka Lake"] },
      { src: "/india/states/odisha/tour-7.jpg", days: "8-10 Days", places: ["Ratnagiri", "Sanaghagra Nature Camp", "Udaygiri", "Khandagiri", "Chilka", "Konark", "Puri", "Bhubaneshwar"] },
      { src: "/india/states/odisha/tour-8.jpg", days: "8-10 Days", places: ["Bhubaneshwar", "Mangalazodi", "Ramchandi Beach", "Bhitarkanika", "Kapilash Sanctuary"] },
    ],
  },
  "punjab": {
    slug: "punjab",
    name: "Punjab",
    tagline: "WHERE NATURE BLENDS WITH HISTORY",
    heroImage: "/india/states/punjab/hero.jpg",
    itineraries: [
      { src: "/india/states/punjab/tour-1.jpg", days: "3-4 Days", places: ["Chandigarh"] },
      { src: "/india/states/punjab/tour-2.jpg", days: "3-4 Days", places: ["Amristar", "Wagah"] },
      { src: "/india/states/punjab/tour-3.jpg", days: "3-4 Days", places: ["Bhatinda"] },
      { src: "/india/states/punjab/tour-4.jpg", days: "3-4 Days", places: ["Jalandhar"] },
      { src: "/india/states/punjab/tour-5.jpg", days: "3-4 Days", places: ["Ludhiana"] },
      { src: "/india/states/punjab/tour-6.jpg", days: "Haryana", places: ["Ambala", "Hisar", "Kurukshetra", "Rohatak", "Sonipet"] },
      { src: "/india/states/punjab/tour-7.jpg", days: "3-4 Days", places: ["Pathankot"] },
      { src: "/india/states/punjab/tour-8.jpg", days: "3-4 Days", places: ["Patiala"] },
    ],
  },
  "rajasthan": {
    slug: "rajasthan",
    name: "Rajasthan",
    tagline: "EXPLORE THE LAND OF THE MAHARAJAS",
    heroImage: "/india/states/rajasthan/hero.jpg",
    itineraries: [
      { src: "/india/states/rajasthan/tour-1.jpg", days: "4-10 Days", places: ["Jaipur", "Alwar", "Ajmer", "Pushkar", "Tonk"] },
      { src: "/india/states/rajasthan/tour-2.jpg", days: "4-10 Days", places: ["Jodhpur", "Ranakpur", "Khichan"] },
      { src: "/india/states/rajasthan/tour-3.jpg", days: "4-10 Days", places: ["Udaipur", "Delwara", "Haldighati"] },
      { src: "/india/states/rajasthan/tour-4.jpg", days: "4-7 Days", places: ["Jaisalmer", "Gadsisar Lake", "Kuldhar"] },
      { src: "/india/states/rajasthan/tour-5.jpg", days: "4-5 Days", places: ["Kumbalgarh", "Chittorgarh"] },
      { src: "/india/states/rajasthan/tour-6.jpg", days: "4-5 Days", places: ["Ranthambore", "Sawai Madhopur"] },
      { src: "/india/states/rajasthan/tour-7.jpg", days: "3-7 Days", places: ["Shekawati", "Bikaner", "Deshnoke"] },
      { src: "/india/states/rajasthan/tour-8.jpg", days: "3-5 Days", places: ["Bharatpur", "Lohagarh Fort"] },
    ],
  },
  "sikkim": {
    slug: "sikkim",
    name: "Sikkim",
    tagline: "WHERE NATURE SMILES",
    heroImage: "/india/states/sikkim/hero.jpg",
    itineraries: [
      { src: "/india/states/sikkim/tour-1.jpg", days: "3-5 Days", places: ["Gangtok"] },
      { src: "/india/states/sikkim/tour-2.jpg", days: "3-5 Days", places: ["Darjeeling", "Gangtok"] },
      { src: "/india/states/sikkim/tour-3.jpg", days: "4-7 Days", places: ["Pelling", "Ravangla", "Gangtok"] },
      { src: "/india/states/sikkim/tour-4.jpg", days: "4-7 Days", places: ["Lachung", "Yumthang", "Lachen", "Gangtok"] },
      { src: "/india/states/sikkim/tour-5.jpg", days: "4-7 Days", places: ["Gurudongmer Lake", "Gangtok"] },
      { src: "/india/states/sikkim/tour-6.jpg", days: "4-7 Days", places: ["Kalimpong", "Gangtok"] },
      { src: "/india/states/sikkim/tour-7.jpg", days: "4-7 Days", places: ["Yuksom", "Gangtok"] },
      { src: "/india/states/sikkim/tour-8.jpg", days: "4-7 Days", places: ["Lava Loleyagaon", "Gangtok"] },
    ],
  },
  "tamil-nadu": {
    slug: "tamil-nadu",
    name: "Tamil Nadu",
    tagline: "SIMPLY ENCHANTING",
    heroImage: "/india/states/tamil-nadu/hero.jpg",
    itineraries: [
      { src: "/india/states/tamil-nadu/tour-1.jpg", days: "Weekend Breaks", places: ["Ex Chennai", "Puducherry", "Mahabalipuram"] },
      { src: "/india/states/tamil-nadu/tour-2.jpg", days: "Hill Stations", places: ["Ooty", "Coonoor", "Kodaikanal", "Yercaud", "Pollachi", "Yelagiri"] },
      { src: "/india/states/tamil-nadu/tour-3.jpg", days: "4-5 Days", places: ["Navagraha Tour", "Ex Chennai"] },
      { src: "/india/states/tamil-nadu/tour-4.jpg", days: "3-4 Days", places: ["Great Chola Temples", "Darasuram", "Thanjavur", "Gangaikondacholapuram"] },
      { src: "/india/states/tamil-nadu/tour-5.jpg", days: "4-5 Days", places: ["Chettinad", "Karaikudi", "Poompuhar", "Sivagangai"] },
      { src: "/india/states/tamil-nadu/tour-6.jpg", days: "3-4 Days", places: ["Trichy", "Kumbakonam", "Thanjavur"] },
      { src: "/india/states/tamil-nadu/tour-7.jpg", days: "3-4 Days", places: ["Kanyakumari", "Rameswaram", "Dhanushkodi"] },
      { src: "/india/states/tamil-nadu/tour-8.jpg", days: "3-4 Days", places: ["Madurai"] },
    ],
  },
  "uttarakhand": {
    slug: "uttarakhand",
    name: "Uttarakhand",
    tagline: "SIMPLY HEAVEN",
    heroImage: "/india/states/uttarakhand/hero.jpg",
    itineraries: [
      { src: "/india/states/uttarakhand/tour-1.jpg", days: "12 Days", places: ["Char Dham Yatra", "Ex New Delhi", "Gangotri", "Yamunotri", "Kedarnath", "Badrinath"] },
      { src: "/india/states/uttarakhand/tour-2.jpg", days: "8 Days", places: ["Do Dham Yatra", "Gangotri", "Yamunotri"] },
      { src: "/india/states/uttarakhand/tour-3.jpg", days: "3-4 Days", places: ["Jim Corbett NP"] },
      { src: "/india/states/uttarakhand/tour-4.jpg", days: "4-7 Days", places: ["Dehradun", "Mussoorie", "Dhanaulti"] },
      { src: "/india/states/uttarakhand/tour-5.jpg", days: "2-4 Days", places: ["Haridwar", "Rishikesh"] },
      { src: "/india/states/uttarakhand/tour-6.jpg", days: "4-10 Days", places: ["Almora", "Binsar", "Ranikhet"] },
      { src: "/india/states/uttarakhand/tour-7.jpg", days: "4-10 Days", places: ["Nainital", "Bhimtal", "Ramgarh"] },
      { src: "/india/states/uttarakhand/tour-8.jpg", days: "4-7 Days", places: ["Auli", "Valley of Flowers"] },
    ],
  },
  "uttar-pradesh": {
    slug: "uttar-pradesh",
    name: "Uttar Pradesh",
    tagline: "WAH TAJ!",
    heroImage: "/india/states/uttar-pradesh/hero.jpg",
    itineraries: [
      { src: "/india/states/uttar-pradesh/tour-1.jpg", days: "4-7 Days", places: ["Agra", "Mathura, Vrindavan"] },
      { src: "/india/states/uttar-pradesh/tour-2.jpg", days: "4-7 Days", places: ["Varanasi", "Sarnath", "Prayagraj"] },
      { src: "/india/states/uttar-pradesh/tour-3.jpg", days: "4-7 Days", places: ["Lucknow", "Dudhwa"] },
      { src: "/india/states/uttar-pradesh/tour-4.jpg", days: "3-5 Days", places: ["Lucknow", "Ayodhya"] },
      { src: "/india/states/uttar-pradesh/tour-5.jpg", days: "3-5 Days", places: ["Dudhwa", "Katarniaghat Sanctuary"] },
      { src: "/india/states/uttar-pradesh/tour-6.jpg", days: "7 Days", places: ["Prayagraj", "Ayodhya", "Lucknow", "Dudhwa"] },
      { src: "/india/states/uttar-pradesh/tour-7.jpg", days: "7 Days", places: ["Varanasi", "Sarnath", "Bodh Gaya"] },
      { src: "/india/states/uttar-pradesh/tour-8.jpg", days: "4 Days", places: ["Prayagraj", "Chitrakoot"] },
    ],
  },
  "west-bengal": {
    slug: "west-bengal",
    name: "West Bengal",
    tagline: "THE SWEETEST PART OF INDIA",
    heroImage: "/india/states/west-bengal/hero.jpg",
    itineraries: [
      { src: "/india/states/west-bengal/tour-1.jpg", days: "4-7 Days", places: ["Kolkata", "Belur Math", "Shantiniketan"] },
      { src: "/india/states/west-bengal/tour-2.jpg", days: "4-7 Days", places: ["Darjeeling", "Kalimpong"] },
      { src: "/india/states/west-bengal/tour-3.jpg", days: "4-7 Days", places: ["Dooars", "Jaldapara"] },
      { src: "/india/states/west-bengal/tour-4.jpg", days: "4-5 Days", places: ["Sundarbans", "Sajnekhali Sanctuary"] },
      { src: "/india/states/west-bengal/tour-5.jpg", days: "7-10 Days", places: ["Siliguri", "Lava", "Kalimpong", "Singalila NP", "Darjeeling"] },
      { src: "/india/states/west-bengal/tour-6.jpg", days: "4-7 Days", places: ["Digha", "Kolkata"] },
      { src: "/india/states/west-bengal/tour-7.jpg", days: "4-7 Days", places: ["Mirik Lake", "Kalimpong", "Darjeeling"] },
      { src: "/india/states/west-bengal/tour-8.jpg", days: "4-6 Days", places: ["Bishnupur", "Kolkata"] },
    ],
  },
  "telangana": {
    slug: "telangana",
    name: "Telangana",
    tagline: "VISIT FOR ALL REASONS AND SEASONS",
    heroImage: "/india/states/telangana/hero.jpg",
    itineraries: [
      { src: "/india/states/telangana/tour-1.jpg", days: "City Break", places: ["Hyderabad"] },
      { src: "/india/states/telangana/tour-2.jpg", days: "Day Trips", places: ["Ex Hyderabad", "Osman Sagar Lake", "Mrugavani NP", "Singur Dam", "Ramoji Film City"] },
      { src: "/india/states/telangana/tour-3.jpg", days: "Weekend Breaks", places: ["Ex Hyderabad", "Bhongir Fort", "Ammapalli", "Medak Fort"] },
      { src: "/india/states/telangana/tour-4.jpg", days: "3-4 Days", places: ["Karimnagar"] },
      { src: "/india/states/telangana/tour-5.jpg", days: "3-4 Days", places: ["Khammam"] },
      { src: "/india/states/telangana/tour-6.jpg", days: "3-4 Days", places: ["Nalagonda"] },
      { src: "/india/states/telangana/tour-7.jpg", days: "3-4 Days", places: ["Nizamabad"] },
      { src: "/india/states/telangana/tour-8.jpg", days: "3-4 Days", places: ["Warangal"] },
    ],
  },
  "northeast": {
    slug: "northeast",
    name: "Northeast",
    tagline: "GATEWAY TO SERENITY",
    heroImage: "/india/states/northeast/hero.jpg",
    itineraries: [
      { src: "/india/states/northeast/tour-1.jpg", days: "4-10 Days", places: ["Arunachal Pradesh"] },
      { src: "/india/states/northeast/tour-2.jpg", days: "4-10 Days", places: ["Assam"] },
      { src: "/india/states/northeast/tour-3.jpg", days: "4-10 Days", places: ["Manipur"] },
      { src: "/india/states/northeast/tour-4.jpg", days: "4-10 Days", places: ["Meghalaya"] },
      { src: "/india/states/northeast/tour-5.jpg", days: "4-10 Days", places: ["Mizoram"] },
      { src: "/india/states/northeast/tour-6.jpg", days: "4-10 Days", places: ["Nagaland"] },
      { src: "/india/states/northeast/tour-7.jpg", days: "4-10 Days", places: ["Tripura"] },
      { src: "/india/states/northeast/tour-8.jpg", days: "4-10 Days", places: ["Sikkim"] },
    ],
  },
  "ladakh": {
    slug: "ladakh",
    name: "Ladakh",
    tagline: "ULTIMATE SCENIC",
    heroImage: "/india/states/ladakh/hero.jpg",
    itineraries: [
      { src: "/india/states/ladakh/tour-1.jpg", days: "5 Days", places: ["Leh", "Mgnetic Hill", "Nubra Valley"] },
      { src: "/india/states/ladakh/tour-2.jpg", days: "6 Days", places: ["Leh", "Magnetic Hill", "Pangong Lake", "Khardung La", "Nubra Valley"] },
      { src: "/india/states/ladakh/tour-3.jpg", days: "7 Days", places: ["Leh", "Magnetic Hill", "Pangong Lake", "Khardung La", "Nubra Valley", "Diskit & Hunder"] },
      { src: "/india/states/ladakh/tour-4.jpg", days: "8 Days", places: ["Leh", "Magnetic Hill", "Pangong Lake", "Khardung La", "Nubra Valley", "Diskit & Hunder", "Uleytokpo"] },
      { src: "/india/states/ladakh/tour-5.jpg", days: "Trekking", places: ["Chilling Trek", "Markha Trek", "Padum"] },
      { src: "/india/states/ladakh/tour-6.jpg", days: "Mountaineering", places: ["Istok Khangiri", "Mentok Peak", "Khag Yatse"] },
      { src: "/india/states/ladakh/tour-7.jpg", days: "8 Days", places: ["Leh", "Magnetic Hill", "Pangong Lake", "Khardung La", "Nubra Valley", "Diskit & Hunder", "Tosmoriri"] },
      { src: "/india/states/ladakh/tour-8.jpg", days: "10 Days", places: ["Leh", "Magnetic Hill", "Pangong Lake", "Khardung La", "Nubra Valley", "Diskit & Hunder", "Tosmoriri", "Uleytokpo"] },
    ],
  },
};
